spring:
  application:
    name: xbt-commandline
  banner:
    location: classpath:/banner/sig.txt    
  cloud:
    config:
      enabled: false            
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non-null    
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true

logging:
  level:
    org.crossroad.sap.tools: error
    org.crossroad.sap.tools.xbp.console: info
