server:
  address: 0.0.0.0
  port: 9090
  ssl:
    key-store: file:C:\data\servers\plm-apps\etc\ssl\tomcat.jks
    key-store-password: NewCertificateTally2022-3!  
  
spring:
  application:
    name: xbt-backend-server
  cloud:
    config:
      enabled: false            
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non-null    
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    org.crossroad.sap.tools.xbp.backend: debug
    org.crossroad.sap.tools.xbp.core: debug
    
xbp:
  jpa:
    jdbc:
      driver-class: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/xbpdb
      username: xbpadmin
      password: admin
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      fetch-size: 2000
      
