//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIPROF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIPROF"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BAPIPROF" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="BAPIPTEXT" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="BAPITYPE" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="BAPIAKTPS" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIPROF", propOrder = {
    "bapiprof",
    "bapiptext",
    "bapitype",
    "bapiaktps"
})
public class BAPIPROF {

    @XmlElement(name = "BAPIPROF", required = true)
    protected String bapiprof;
    @XmlElement(name = "BAPIPTEXT", required = true)
    protected String bapiptext;
    @XmlElement(name = "BAPITYPE", required = true)
    protected String bapitype;
    @XmlElement(name = "BAPIAKTPS", required = true)
    protected String bapiaktps;

    /**
     * Gets the value of the bapiprof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAPIPROF() {
        return bapiprof;
    }

    /**
     * Sets the value of the bapiprof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAPIPROF(String value) {
        this.bapiprof = value;
    }

    /**
     * Gets the value of the bapiptext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAPIPTEXT() {
        return bapiptext;
    }

    /**
     * Sets the value of the bapiptext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAPIPTEXT(String value) {
        this.bapiptext = value;
    }

    /**
     * Gets the value of the bapitype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAPITYPE() {
        return bapitype;
    }

    /**
     * Sets the value of the bapitype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAPITYPE(String value) {
        this.bapitype = value;
    }

    /**
     * Gets the value of the bapiaktps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAPIAKTPS() {
        return bapiaktps;
    }

    /**
     * Sets the value of the bapiaktps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAPIAKTPS(String value) {
        this.bapiaktps = value;
    }

}
