//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIUCLASS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIUCLASS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LIC_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="SPEC_VERS" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="COUNTRY_SURCHARGE" type="{urn:sap-com:document:sap:rfc:functions}decimal3.0"/&gt;
 *         &lt;element name="SUBSTITUTE_FROM" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="SUBSTITUTE_UNTIL" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="SYSID" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="CLIENT" type="{urn:sap-com:document:sap:rfc:functions}clnt3"/&gt;
 *         &lt;element name="BNAME_CHARGEABLE" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIUCLASS", propOrder = {
    "lictype",
    "specvers",
    "countrysurcharge",
    "substitutefrom",
    "substituteuntil",
    "sysid",
    "client",
    "bnamechargeable"
})
public class BAPIUCLASS {

    @XmlElement(name = "LIC_TYPE", required = true)
    protected String lictype;
    @XmlElement(name = "SPEC_VERS", required = true)
    protected String specvers;
    @XmlElement(name = "COUNTRY_SURCHARGE", required = true)
    protected BigDecimal countrysurcharge;
    @XmlElement(name = "SUBSTITUTE_FROM", required = true)
    protected String substitutefrom;
    @XmlElement(name = "SUBSTITUTE_UNTIL", required = true)
    protected String substituteuntil;
    @XmlElement(name = "SYSID", required = true)
    protected String sysid;
    @XmlElement(name = "CLIENT", required = true)
    protected String client;
    @XmlElement(name = "BNAME_CHARGEABLE", required = true)
    protected String bnamechargeable;

    /**
     * Gets the value of the lictype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLICTYPE() {
        return lictype;
    }

    /**
     * Sets the value of the lictype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLICTYPE(String value) {
        this.lictype = value;
    }

    /**
     * Gets the value of the specvers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPECVERS() {
        return specvers;
    }

    /**
     * Sets the value of the specvers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPECVERS(String value) {
        this.specvers = value;
    }

    /**
     * Gets the value of the countrysurcharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCOUNTRYSURCHARGE() {
        return countrysurcharge;
    }

    /**
     * Sets the value of the countrysurcharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCOUNTRYSURCHARGE(BigDecimal value) {
        this.countrysurcharge = value;
    }

    /**
     * Gets the value of the substitutefrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBSTITUTEFROM() {
        return substitutefrom;
    }

    /**
     * Sets the value of the substitutefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBSTITUTEFROM(String value) {
        this.substitutefrom = value;
    }

    /**
     * Gets the value of the substituteuntil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBSTITUTEUNTIL() {
        return substituteuntil;
    }

    /**
     * Sets the value of the substituteuntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBSTITUTEUNTIL(String value) {
        this.substituteuntil = value;
    }

    /**
     * Gets the value of the sysid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYSID() {
        return sysid;
    }

    /**
     * Sets the value of the sysid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYSID(String value) {
        this.sysid = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLIENT() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLIENT(String value) {
        this.client = value;
    }

    /**
     * Gets the value of the bnamechargeable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBNAMECHARGEABLE() {
        return bnamechargeable;
    }

    /**
     * Sets the value of the bnamechargeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBNAMECHARGEABLE(String value) {
        this.bnamechargeable = value;
    }

}
