//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIAGR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIAGR"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AGR_NAME" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="FROM_DAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="TO_DAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="AGR_TEXT" type="{urn:sap-com:document:sap:rfc:functions}char80"/&gt;
 *         &lt;element name="ORG_FLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIAGR", propOrder = {
    "agrname",
    "fromdat",
    "todat",
    "agrtext",
    "orgflag"
})
public class BAPIAGR {

    @XmlElement(name = "AGR_NAME", required = true)
    protected String agrname;
    @XmlElement(name = "FROM_DAT", required = true)
    protected String fromdat;
    @XmlElement(name = "TO_DAT", required = true)
    protected String todat;
    @XmlElement(name = "AGR_TEXT", required = true)
    protected String agrtext;
    @XmlElement(name = "ORG_FLAG", required = true)
    protected String orgflag;

    /**
     * Gets the value of the agrname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGRNAME() {
        return agrname;
    }

    /**
     * Sets the value of the agrname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGRNAME(String value) {
        this.agrname = value;
    }

    /**
     * Gets the value of the fromdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFROMDAT() {
        return fromdat;
    }

    /**
     * Sets the value of the fromdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROMDAT(String value) {
        this.fromdat = value;
    }

    /**
     * Gets the value of the todat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTODAT() {
        return todat;
    }

    /**
     * Sets the value of the todat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTODAT(String value) {
        this.todat = value;
    }

    /**
     * Gets the value of the agrtext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGRTEXT() {
        return agrtext;
    }

    /**
     * Sets the value of the agrtext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGRTEXT(String value) {
        this.agrtext = value;
    }

    /**
     * Gets the value of the orgflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGFLAG() {
        return orgflag;
    }

    /**
     * Sets the value of the orgflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGFLAG(String value) {
        this.orgflag = value;
    }

}
