//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIUCLASSX complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIUCLASSX"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UCLASS" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="UCLASSSYS" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIUCLASSX", propOrder = {
    "uclass",
    "uclasssys"
})
public class BAPIUCLASSX {

    @XmlElement(name = "UCLASS", required = true)
    protected String uclass;
    @XmlElement(name = "UCLASSSYS", required = true)
    protected String uclasssys;

    /**
     * Gets the value of the uclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCLASS() {
        return uclass;
    }

    /**
     * Sets the value of the uclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCLASS(String value) {
        this.uclass = value;
    }

    /**
     * Gets the value of the uclasssys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCLASSSYS() {
        return uclasssys;
    }

    /**
     * Sets the value of the uclasssys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCLASSSYS(String value) {
        this.uclasssys = value;
    }

}
