//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPISLOCKD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPISLOCKD"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WRNG_LOGON" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="LOCAL_LOCK" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="GLOB_LOCK" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="NO_USER_PW" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPISLOCKD", propOrder = {
    "wrnglogon",
    "locallock",
    "globlock",
    "nouserpw"
})
public class BAPISLOCKD {

    @XmlElement(name = "WRNG_LOGON", required = true)
    protected String wrnglogon;
    @XmlElement(name = "LOCAL_LOCK", required = true)
    protected String locallock;
    @XmlElement(name = "GLOB_LOCK", required = true)
    protected String globlock;
    @XmlElement(name = "NO_USER_PW", required = true)
    protected String nouserpw;

    /**
     * Gets the value of the wrnglogon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWRNGLOGON() {
        return wrnglogon;
    }

    /**
     * Sets the value of the wrnglogon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWRNGLOGON(String value) {
        this.wrnglogon = value;
    }

    /**
     * Gets the value of the locallock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALLOCK() {
        return locallock;
    }

    /**
     * Sets the value of the locallock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALLOCK(String value) {
        this.locallock = value;
    }

    /**
     * Gets the value of the globlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLOBLOCK() {
        return globlock;
    }

    /**
     * Sets the value of the globlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGLOBLOCK(String value) {
        this.globlock = value;
    }

    /**
     * Gets the value of the nouserpw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOUSERPW() {
        return nouserpw;
    }

    /**
     * Sets the value of the nouserpw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOUSERPW(String value) {
        this.nouserpw = value;
    }

}
