//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIUSEXTIDHEAD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIUSEXTIDHEAD"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SEQ_NO_ID" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="TYPE" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="CODE_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="EXTID_LEN" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="ISSUER_LEN" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="SERIAL_LEN" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="VALITYINFO" type="{urn:sap-com:document:sap:rfc:functions}byte16"/&gt;
 *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="STATUS" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="EXTFLAG" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIUSEXTIDHEAD", propOrder = {
    "seqnoid",
    "type",
    "codetype",
    "extidlen",
    "issuerlen",
    "seriallen",
    "valityinfo",
    "version",
    "status",
    "extflag"
})
public class BAPIUSEXTIDHEAD {

    @XmlElement(name = "SEQ_NO_ID", required = true)
    protected String seqnoid;
    @XmlElement(name = "TYPE", required = true)
    protected String type;
    @XmlElement(name = "CODE_TYPE", required = true)
    protected String codetype;
    @XmlElement(name = "EXTID_LEN")
    protected short extidlen;
    @XmlElement(name = "ISSUER_LEN")
    protected short issuerlen;
    @XmlElement(name = "SERIAL_LEN")
    protected short seriallen;
    @XmlElement(name = "VALITYINFO", required = true)
    protected byte[] valityinfo;
    @XmlElement(name = "VERSION")
    @XmlSchemaType(name = "unsignedByte")
    protected short version;
    @XmlElement(name = "STATUS", required = true)
    protected String status;
    @XmlElement(name = "EXTFLAG", required = true)
    protected String extflag;

    /**
     * Gets the value of the seqnoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQNOID() {
        return seqnoid;
    }

    /**
     * Sets the value of the seqnoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQNOID(String value) {
        this.seqnoid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the codetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODETYPE() {
        return codetype;
    }

    /**
     * Sets the value of the codetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODETYPE(String value) {
        this.codetype = value;
    }

    /**
     * Gets the value of the extidlen property.
     * 
     */
    public short getEXTIDLEN() {
        return extidlen;
    }

    /**
     * Sets the value of the extidlen property.
     * 
     */
    public void setEXTIDLEN(short value) {
        this.extidlen = value;
    }

    /**
     * Gets the value of the issuerlen property.
     * 
     */
    public short getISSUERLEN() {
        return issuerlen;
    }

    /**
     * Sets the value of the issuerlen property.
     * 
     */
    public void setISSUERLEN(short value) {
        this.issuerlen = value;
    }

    /**
     * Gets the value of the seriallen property.
     * 
     */
    public short getSERIALLEN() {
        return seriallen;
    }

    /**
     * Sets the value of the seriallen property.
     * 
     */
    public void setSERIALLEN(short value) {
        this.seriallen = value;
    }

    /**
     * Gets the value of the valityinfo property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getVALITYINFO() {
        return valityinfo;
    }

    /**
     * Sets the value of the valityinfo property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setVALITYINFO(byte[] value) {
        this.valityinfo = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public short getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVERSION(short value) {
        this.version = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the extflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTFLAG() {
        return extflag;
    }

    /**
     * Sets the value of the extflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTFLAG(String value) {
        this.extflag = value;
    }

}
