//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIDEFAX complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIDEFAX"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="STCOD" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SPLD" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SPLG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SPDB" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="SPDA" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="DATFM" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="DCPFM" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="LANGU" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="CATT" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="KOSTL" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="START_MENU" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="TIMEFM" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIDEFAX", propOrder = {
    "stcod",
    "spld",
    "splg",
    "spdb",
    "spda",
    "datfm",
    "dcpfm",
    "langu",
    "catt",
    "kostl",
    "startmenu",
    "timefm"
})
public class BAPIDEFAX {

    @XmlElement(name = "STCOD", required = true)
    protected String stcod;
    @XmlElement(name = "SPLD", required = true)
    protected String spld;
    @XmlElement(name = "SPLG", required = true)
    protected String splg;
    @XmlElement(name = "SPDB", required = true)
    protected String spdb;
    @XmlElement(name = "SPDA", required = true)
    protected String spda;
    @XmlElement(name = "DATFM", required = true)
    protected String datfm;
    @XmlElement(name = "DCPFM", required = true)
    protected String dcpfm;
    @XmlElement(name = "LANGU", required = true)
    protected String langu;
    @XmlElement(name = "CATT", required = true)
    protected String catt;
    @XmlElement(name = "KOSTL", required = true)
    protected String kostl;
    @XmlElement(name = "START_MENU", required = true)
    protected String startmenu;
    @XmlElement(name = "TIMEFM", required = true)
    protected String timefm;

    /**
     * Gets the value of the stcod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTCOD() {
        return stcod;
    }

    /**
     * Sets the value of the stcod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTCOD(String value) {
        this.stcod = value;
    }

    /**
     * Gets the value of the spld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLD() {
        return spld;
    }

    /**
     * Sets the value of the spld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLD(String value) {
        this.spld = value;
    }

    /**
     * Gets the value of the splg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLG() {
        return splg;
    }

    /**
     * Sets the value of the splg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLG(String value) {
        this.splg = value;
    }

    /**
     * Gets the value of the spdb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPDB() {
        return spdb;
    }

    /**
     * Sets the value of the spdb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPDB(String value) {
        this.spdb = value;
    }

    /**
     * Gets the value of the spda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPDA() {
        return spda;
    }

    /**
     * Sets the value of the spda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPDA(String value) {
        this.spda = value;
    }

    /**
     * Gets the value of the datfm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATFM() {
        return datfm;
    }

    /**
     * Sets the value of the datfm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATFM(String value) {
        this.datfm = value;
    }

    /**
     * Gets the value of the dcpfm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCPFM() {
        return dcpfm;
    }

    /**
     * Sets the value of the dcpfm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCPFM(String value) {
        this.dcpfm = value;
    }

    /**
     * Gets the value of the langu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGU() {
        return langu;
    }

    /**
     * Sets the value of the langu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGU(String value) {
        this.langu = value;
    }

    /**
     * Gets the value of the catt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATT() {
        return catt;
    }

    /**
     * Sets the value of the catt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATT(String value) {
        this.catt = value;
    }

    /**
     * Gets the value of the kostl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKOSTL() {
        return kostl;
    }

    /**
     * Sets the value of the kostl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKOSTL(String value) {
        this.kostl = value;
    }

    /**
     * Gets the value of the startmenu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTARTMENU() {
        return startmenu;
    }

    /**
     * Sets the value of the startmenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTARTMENU(String value) {
        this.startmenu = value;
    }

    /**
     * Gets the value of the timefm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEFM() {
        return timefm;
    }

    /**
     * Sets the value of the timefm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEFM(String value) {
        this.timefm = value;
    }

}
