//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIUSEXTIDPART complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIUSEXTIDPART"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SEQ_NO_ID" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="FIELDNAME" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="SEQ_NO_PART" type="{urn:sap-com:document:sap:rfc:functions}numeric4"/&gt;
 *         &lt;element name="PART_DATA" type="{urn:sap-com:document:sap:rfc:functions}char192"/&gt;
 *         &lt;element name="EXTFLAG" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIUSEXTIDPART", propOrder = {
    "seqnoid",
    "fieldname",
    "seqnopart",
    "partdata",
    "extflag"
})
public class BAPIUSEXTIDPART {

    @XmlElement(name = "SEQ_NO_ID", required = true)
    protected String seqnoid;
    @XmlElement(name = "FIELDNAME", required = true)
    protected String fieldname;
    @XmlElement(name = "SEQ_NO_PART", required = true)
    protected String seqnopart;
    @XmlElement(name = "PART_DATA", required = true)
    protected String partdata;
    @XmlElement(name = "EXTFLAG", required = true)
    protected String extflag;

    /**
     * Gets the value of the seqnoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQNOID() {
        return seqnoid;
    }

    /**
     * Sets the value of the seqnoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQNOID(String value) {
        this.seqnoid = value;
    }

    /**
     * Gets the value of the fieldname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIELDNAME() {
        return fieldname;
    }

    /**
     * Sets the value of the fieldname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIELDNAME(String value) {
        this.fieldname = value;
    }

    /**
     * Gets the value of the seqnopart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQNOPART() {
        return seqnopart;
    }

    /**
     * Sets the value of the seqnopart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQNOPART(String value) {
        this.seqnopart = value;
    }

    /**
     * Gets the value of the partdata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTDATA() {
        return partdata;
    }

    /**
     * Sets the value of the partdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTDATA(String value) {
        this.partdata = value;
    }

    /**
     * Gets the value of the extflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTFLAG() {
        return extflag;
    }

    /**
     * Sets the value of the extflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTFLAG(String value) {
        this.extflag = value;
    }

}
