//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ADDCOMREM" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPICOMREM" minOccurs="0"/&gt;
 *         &lt;element name="ADDCOMX" type="{urn:sap-com:document:sap:rfc:functions}BAPIADCOMX" minOccurs="0"/&gt;
 *         &lt;element name="ADDFAX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADFAX" minOccurs="0"/&gt;
 *         &lt;element name="ADDPAG" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADPAG" minOccurs="0"/&gt;
 *         &lt;element name="ADDPRT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADPRT" minOccurs="0"/&gt;
 *         &lt;element name="ADDRESS" type="{urn:sap-com:document:sap:rfc:functions}BAPIADDR3" minOccurs="0"/&gt;
 *         &lt;element name="ADDRESSX" type="{urn:sap-com:document:sap:rfc:functions}BAPIADDR3X" minOccurs="0"/&gt;
 *         &lt;element name="ADDRFC" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADRFC" minOccurs="0"/&gt;
 *         &lt;element name="ADDRML" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADRML" minOccurs="0"/&gt;
 *         &lt;element name="ADDSMTP" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADSMTP" minOccurs="0"/&gt;
 *         &lt;element name="ADDSSF" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADSSF" minOccurs="0"/&gt;
 *         &lt;element name="ADDTEL" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTEL" minOccurs="0"/&gt;
 *         &lt;element name="ADDTLX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTLX" minOccurs="0"/&gt;
 *         &lt;element name="ADDTTX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTTX" minOccurs="0"/&gt;
 *         &lt;element name="ADDURI" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADURI" minOccurs="0"/&gt;
 *         &lt;element name="ADDX400" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADX400" minOccurs="0"/&gt;
 *         &lt;element name="ALIAS" type="{urn:sap-com:document:sap:rfc:functions}BAPIALIAS" minOccurs="0"/&gt;
 *         &lt;element name="ALIASX" type="{urn:sap-com:document:sap:rfc:functions}BAPIALIASX" minOccurs="0"/&gt;
 *         &lt;element name="BACK_DISTRIBUTION" type="{urn:sap-com:document:sap:rfc:functions}BAPIFLAG" minOccurs="0"/&gt;
 *         &lt;element name="COMPANY" type="{urn:sap-com:document:sap:rfc:functions}BAPIUSCOMP" minOccurs="0"/&gt;
 *         &lt;element name="COMPANYX" type="{urn:sap-com:document:sap:rfc:functions}BAPIUSCOMX" minOccurs="0"/&gt;
 *         &lt;element name="DEFAULTS" type="{urn:sap-com:document:sap:rfc:functions}BAPIDEFAUL" minOccurs="0"/&gt;
 *         &lt;element name="DEFAULTSX" type="{urn:sap-com:document:sap:rfc:functions}BAPIDEFAX" minOccurs="0"/&gt;
 *         &lt;element name="DESCRIPTION" type="{urn:sap-com:document:sap:rfc:functions}BAPIUSDESC" minOccurs="0"/&gt;
 *         &lt;element name="DESCRIPTIONX" type="{urn:sap-com:document:sap:rfc:functions}BAPIUSDESCX" minOccurs="0"/&gt;
 *         &lt;element name="EXTIDHEAD" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUSEXTIDHEAD" minOccurs="0"/&gt;
 *         &lt;element name="EXTIDPART" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUSEXTIDPART" minOccurs="0"/&gt;
 *         &lt;element name="EXTIDSX" type="{urn:sap-com:document:sap:rfc:functions}BAPIUSEXTIDX" minOccurs="0"/&gt;
 *         &lt;element name="GENERATE_PWD" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *         &lt;element name="GROUPS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIGROUPS" minOccurs="0"/&gt;
 *         &lt;element name="GROUPSX" type="{urn:sap-com:document:sap:rfc:functions}BAPIGROUPX" minOccurs="0"/&gt;
 *         &lt;element name="LOGONDATA" type="{urn:sap-com:document:sap:rfc:functions}BAPILOGOND" minOccurs="0"/&gt;
 *         &lt;element name="LOGONDATAX" type="{urn:sap-com:document:sap:rfc:functions}BAPILOGONX" minOccurs="0"/&gt;
 *         &lt;element name="PARAMETER" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIPARAM" minOccurs="0"/&gt;
 *         &lt;element name="PARAMETER1" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIPARAM1" minOccurs="0"/&gt;
 *         &lt;element name="PARAMETERX" type="{urn:sap-com:document:sap:rfc:functions}BAPIPARAMX" minOccurs="0"/&gt;
 *         &lt;element name="PASSWORD" type="{urn:sap-com:document:sap:rfc:functions}BAPIPWD" minOccurs="0"/&gt;
 *         &lt;element name="PASSWORDX" type="{urn:sap-com:document:sap:rfc:functions}BAPIPWDX" minOccurs="0"/&gt;
 *         &lt;element name="PRODUCTIVE_PWD" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *         &lt;element name="REF_USER" type="{urn:sap-com:document:sap:rfc:functions}BAPIREFUS" minOccurs="0"/&gt;
 *         &lt;element name="REF_USERX" type="{urn:sap-com:document:sap:rfc:functions}BAPIREFUSX" minOccurs="0"/&gt;
 *         &lt;element name="RETURN" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIRET2"/&gt;
 *         &lt;element name="SNC" type="{urn:sap-com:document:sap:rfc:functions}BAPISNCU" minOccurs="0"/&gt;
 *         &lt;element name="SNCX" type="{urn:sap-com:document:sap:rfc:functions}BAPISNCUX" minOccurs="0"/&gt;
 *         &lt;element name="UCLASS" type="{urn:sap-com:document:sap:rfc:functions}BAPIUCLASS" minOccurs="0"/&gt;
 *         &lt;element name="UCLASSSYS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUCLASSSYS" minOccurs="0"/&gt;
 *         &lt;element name="UCLASSX" type="{urn:sap-com:document:sap:rfc:functions}BAPIUCLASSX" minOccurs="0"/&gt;
 *         &lt;element name="USERNAME" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addcomrem",
    "addcomx",
    "addfax",
    "addpag",
    "addprt",
    "address",
    "addressx",
    "addrfc",
    "addrml",
    "addsmtp",
    "addssf",
    "addtel",
    "addtlx",
    "addttx",
    "adduri",
    "addx400",
    "alias",
    "aliasx",
    "backdistribution",
    "company",
    "companyx",
    "defaults",
    "defaultsx",
    "description",
    "descriptionx",
    "extidhead",
    "extidpart",
    "extidsx",
    "generatepwd",
    "groups",
    "groupsx",
    "logondata",
    "logondatax",
    "parameter",
    "parameter1",
    "parameterx",
    "password",
    "passwordx",
    "productivepwd",
    "refuser",
    "refuserx",
    "_return",
    "snc",
    "sncx",
    "uclass",
    "uclasssys",
    "uclassx",
    "username"
})
@XmlRootElement(name = "BAPI_USER_CHANGE")
public class BAPIUSERCHANGE {

    @XmlElement(name = "ADDCOMREM")
    protected TABLEOFBAPICOMREM addcomrem;
    @XmlElement(name = "ADDCOMX")
    protected BAPIADCOMX addcomx;
    @XmlElement(name = "ADDFAX")
    protected TABLEOFBAPIADFAX addfax;
    @XmlElement(name = "ADDPAG")
    protected TABLEOFBAPIADPAG addpag;
    @XmlElement(name = "ADDPRT")
    protected TABLEOFBAPIADPRT addprt;
    @XmlElement(name = "ADDRESS")
    protected BAPIADDR3 address;
    @XmlElement(name = "ADDRESSX")
    protected BAPIADDR3X addressx;
    @XmlElement(name = "ADDRFC")
    protected TABLEOFBAPIADRFC addrfc;
    @XmlElement(name = "ADDRML")
    protected TABLEOFBAPIADRML addrml;
    @XmlElement(name = "ADDSMTP")
    protected TABLEOFBAPIADSMTP addsmtp;
    @XmlElement(name = "ADDSSF")
    protected TABLEOFBAPIADSSF addssf;
    @XmlElement(name = "ADDTEL")
    protected TABLEOFBAPIADTEL addtel;
    @XmlElement(name = "ADDTLX")
    protected TABLEOFBAPIADTLX addtlx;
    @XmlElement(name = "ADDTTX")
    protected TABLEOFBAPIADTTX addttx;
    @XmlElement(name = "ADDURI")
    protected TABLEOFBAPIADURI adduri;
    @XmlElement(name = "ADDX400")
    protected TABLEOFBAPIADX400 addx400;
    @XmlElement(name = "ALIAS")
    protected BAPIALIAS alias;
    @XmlElement(name = "ALIASX")
    protected BAPIALIASX aliasx;
    @XmlElement(name = "BACK_DISTRIBUTION")
    protected BAPIFLAG backdistribution;
    @XmlElement(name = "COMPANY")
    protected BAPIUSCOMP company;
    @XmlElement(name = "COMPANYX")
    protected BAPIUSCOMX companyx;
    @XmlElement(name = "DEFAULTS")
    protected BAPIDEFAUL defaults;
    @XmlElement(name = "DEFAULTSX")
    protected BAPIDEFAX defaultsx;
    @XmlElement(name = "DESCRIPTION")
    protected BAPIUSDESC description;
    @XmlElement(name = "DESCRIPTIONX")
    protected BAPIUSDESCX descriptionx;
    @XmlElement(name = "EXTIDHEAD")
    protected TABLEOFBAPIUSEXTIDHEAD extidhead;
    @XmlElement(name = "EXTIDPART")
    protected TABLEOFBAPIUSEXTIDPART extidpart;
    @XmlElement(name = "EXTIDSX")
    protected BAPIUSEXTIDX extidsx;
    @XmlElement(name = "GENERATE_PWD")
    protected String generatepwd;
    @XmlElement(name = "GROUPS")
    protected TABLEOFBAPIGROUPS groups;
    @XmlElement(name = "GROUPSX")
    protected BAPIGROUPX groupsx;
    @XmlElement(name = "LOGONDATA")
    protected BAPILOGOND logondata;
    @XmlElement(name = "LOGONDATAX")
    protected BAPILOGONX logondatax;
    @XmlElement(name = "PARAMETER")
    protected TABLEOFBAPIPARAM parameter;
    @XmlElement(name = "PARAMETER1")
    protected TABLEOFBAPIPARAM1 parameter1;
    @XmlElement(name = "PARAMETERX")
    protected BAPIPARAMX parameterx;
    @XmlElement(name = "PASSWORD")
    protected BAPIPWD password;
    @XmlElement(name = "PASSWORDX")
    protected BAPIPWDX passwordx;
    @XmlElement(name = "PRODUCTIVE_PWD")
    protected String productivepwd;
    @XmlElement(name = "REF_USER")
    protected BAPIREFUS refuser;
    @XmlElement(name = "REF_USERX")
    protected BAPIREFUSX refuserx;
    @XmlElement(name = "RETURN", required = true)
    protected TABLEOFBAPIRET2 _return;
    @XmlElement(name = "SNC")
    protected BAPISNCU snc;
    @XmlElement(name = "SNCX")
    protected BAPISNCUX sncx;
    @XmlElement(name = "UCLASS")
    protected BAPIUCLASS uclass;
    @XmlElement(name = "UCLASSSYS")
    protected TABLEOFBAPIUCLASSSYS uclasssys;
    @XmlElement(name = "UCLASSX")
    protected BAPIUCLASSX uclassx;
    @XmlElement(name = "USERNAME", required = true)
    protected String username;

    /**
     * Gets the value of the addcomrem property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPICOMREM }
     *     
     */
    public TABLEOFBAPICOMREM getADDCOMREM() {
        return addcomrem;
    }

    /**
     * Sets the value of the addcomrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPICOMREM }
     *     
     */
    public void setADDCOMREM(TABLEOFBAPICOMREM value) {
        this.addcomrem = value;
    }

    /**
     * Gets the value of the addcomx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIADCOMX }
     *     
     */
    public BAPIADCOMX getADDCOMX() {
        return addcomx;
    }

    /**
     * Sets the value of the addcomx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIADCOMX }
     *     
     */
    public void setADDCOMX(BAPIADCOMX value) {
        this.addcomx = value;
    }

    /**
     * Gets the value of the addfax property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADFAX }
     *     
     */
    public TABLEOFBAPIADFAX getADDFAX() {
        return addfax;
    }

    /**
     * Sets the value of the addfax property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADFAX }
     *     
     */
    public void setADDFAX(TABLEOFBAPIADFAX value) {
        this.addfax = value;
    }

    /**
     * Gets the value of the addpag property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADPAG }
     *     
     */
    public TABLEOFBAPIADPAG getADDPAG() {
        return addpag;
    }

    /**
     * Sets the value of the addpag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADPAG }
     *     
     */
    public void setADDPAG(TABLEOFBAPIADPAG value) {
        this.addpag = value;
    }

    /**
     * Gets the value of the addprt property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADPRT }
     *     
     */
    public TABLEOFBAPIADPRT getADDPRT() {
        return addprt;
    }

    /**
     * Sets the value of the addprt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADPRT }
     *     
     */
    public void setADDPRT(TABLEOFBAPIADPRT value) {
        this.addprt = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIADDR3 }
     *     
     */
    public BAPIADDR3 getADDRESS() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIADDR3 }
     *     
     */
    public void setADDRESS(BAPIADDR3 value) {
        this.address = value;
    }

    /**
     * Gets the value of the addressx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIADDR3X }
     *     
     */
    public BAPIADDR3X getADDRESSX() {
        return addressx;
    }

    /**
     * Sets the value of the addressx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIADDR3X }
     *     
     */
    public void setADDRESSX(BAPIADDR3X value) {
        this.addressx = value;
    }

    /**
     * Gets the value of the addrfc property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADRFC }
     *     
     */
    public TABLEOFBAPIADRFC getADDRFC() {
        return addrfc;
    }

    /**
     * Sets the value of the addrfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADRFC }
     *     
     */
    public void setADDRFC(TABLEOFBAPIADRFC value) {
        this.addrfc = value;
    }

    /**
     * Gets the value of the addrml property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADRML }
     *     
     */
    public TABLEOFBAPIADRML getADDRML() {
        return addrml;
    }

    /**
     * Sets the value of the addrml property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADRML }
     *     
     */
    public void setADDRML(TABLEOFBAPIADRML value) {
        this.addrml = value;
    }

    /**
     * Gets the value of the addsmtp property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADSMTP }
     *     
     */
    public TABLEOFBAPIADSMTP getADDSMTP() {
        return addsmtp;
    }

    /**
     * Sets the value of the addsmtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADSMTP }
     *     
     */
    public void setADDSMTP(TABLEOFBAPIADSMTP value) {
        this.addsmtp = value;
    }

    /**
     * Gets the value of the addssf property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADSSF }
     *     
     */
    public TABLEOFBAPIADSSF getADDSSF() {
        return addssf;
    }

    /**
     * Sets the value of the addssf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADSSF }
     *     
     */
    public void setADDSSF(TABLEOFBAPIADSSF value) {
        this.addssf = value;
    }

    /**
     * Gets the value of the addtel property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTEL }
     *     
     */
    public TABLEOFBAPIADTEL getADDTEL() {
        return addtel;
    }

    /**
     * Sets the value of the addtel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTEL }
     *     
     */
    public void setADDTEL(TABLEOFBAPIADTEL value) {
        this.addtel = value;
    }

    /**
     * Gets the value of the addtlx property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTLX }
     *     
     */
    public TABLEOFBAPIADTLX getADDTLX() {
        return addtlx;
    }

    /**
     * Sets the value of the addtlx property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTLX }
     *     
     */
    public void setADDTLX(TABLEOFBAPIADTLX value) {
        this.addtlx = value;
    }

    /**
     * Gets the value of the addttx property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTTX }
     *     
     */
    public TABLEOFBAPIADTTX getADDTTX() {
        return addttx;
    }

    /**
     * Sets the value of the addttx property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTTX }
     *     
     */
    public void setADDTTX(TABLEOFBAPIADTTX value) {
        this.addttx = value;
    }

    /**
     * Gets the value of the adduri property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADURI }
     *     
     */
    public TABLEOFBAPIADURI getADDURI() {
        return adduri;
    }

    /**
     * Sets the value of the adduri property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADURI }
     *     
     */
    public void setADDURI(TABLEOFBAPIADURI value) {
        this.adduri = value;
    }

    /**
     * Gets the value of the addx400 property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADX400 }
     *     
     */
    public TABLEOFBAPIADX400 getADDX400() {
        return addx400;
    }

    /**
     * Sets the value of the addx400 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADX400 }
     *     
     */
    public void setADDX400(TABLEOFBAPIADX400 value) {
        this.addx400 = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIALIAS }
     *     
     */
    public BAPIALIAS getALIAS() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIALIAS }
     *     
     */
    public void setALIAS(BAPIALIAS value) {
        this.alias = value;
    }

    /**
     * Gets the value of the aliasx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIALIASX }
     *     
     */
    public BAPIALIASX getALIASX() {
        return aliasx;
    }

    /**
     * Sets the value of the aliasx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIALIASX }
     *     
     */
    public void setALIASX(BAPIALIASX value) {
        this.aliasx = value;
    }

    /**
     * Gets the value of the backdistribution property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIFLAG }
     *     
     */
    public BAPIFLAG getBACKDISTRIBUTION() {
        return backdistribution;
    }

    /**
     * Sets the value of the backdistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIFLAG }
     *     
     */
    public void setBACKDISTRIBUTION(BAPIFLAG value) {
        this.backdistribution = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUSCOMP }
     *     
     */
    public BAPIUSCOMP getCOMPANY() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUSCOMP }
     *     
     */
    public void setCOMPANY(BAPIUSCOMP value) {
        this.company = value;
    }

    /**
     * Gets the value of the companyx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUSCOMX }
     *     
     */
    public BAPIUSCOMX getCOMPANYX() {
        return companyx;
    }

    /**
     * Sets the value of the companyx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUSCOMX }
     *     
     */
    public void setCOMPANYX(BAPIUSCOMX value) {
        this.companyx = value;
    }

    /**
     * Gets the value of the defaults property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIDEFAUL }
     *     
     */
    public BAPIDEFAUL getDEFAULTS() {
        return defaults;
    }

    /**
     * Sets the value of the defaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIDEFAUL }
     *     
     */
    public void setDEFAULTS(BAPIDEFAUL value) {
        this.defaults = value;
    }

    /**
     * Gets the value of the defaultsx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIDEFAX }
     *     
     */
    public BAPIDEFAX getDEFAULTSX() {
        return defaultsx;
    }

    /**
     * Sets the value of the defaultsx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIDEFAX }
     *     
     */
    public void setDEFAULTSX(BAPIDEFAX value) {
        this.defaultsx = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUSDESC }
     *     
     */
    public BAPIUSDESC getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUSDESC }
     *     
     */
    public void setDESCRIPTION(BAPIUSDESC value) {
        this.description = value;
    }

    /**
     * Gets the value of the descriptionx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUSDESCX }
     *     
     */
    public BAPIUSDESCX getDESCRIPTIONX() {
        return descriptionx;
    }

    /**
     * Sets the value of the descriptionx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUSDESCX }
     *     
     */
    public void setDESCRIPTIONX(BAPIUSDESCX value) {
        this.descriptionx = value;
    }

    /**
     * Gets the value of the extidhead property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUSEXTIDHEAD }
     *     
     */
    public TABLEOFBAPIUSEXTIDHEAD getEXTIDHEAD() {
        return extidhead;
    }

    /**
     * Sets the value of the extidhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUSEXTIDHEAD }
     *     
     */
    public void setEXTIDHEAD(TABLEOFBAPIUSEXTIDHEAD value) {
        this.extidhead = value;
    }

    /**
     * Gets the value of the extidpart property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUSEXTIDPART }
     *     
     */
    public TABLEOFBAPIUSEXTIDPART getEXTIDPART() {
        return extidpart;
    }

    /**
     * Sets the value of the extidpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUSEXTIDPART }
     *     
     */
    public void setEXTIDPART(TABLEOFBAPIUSEXTIDPART value) {
        this.extidpart = value;
    }

    /**
     * Gets the value of the extidsx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUSEXTIDX }
     *     
     */
    public BAPIUSEXTIDX getEXTIDSX() {
        return extidsx;
    }

    /**
     * Sets the value of the extidsx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUSEXTIDX }
     *     
     */
    public void setEXTIDSX(BAPIUSEXTIDX value) {
        this.extidsx = value;
    }

    /**
     * Gets the value of the generatepwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERATEPWD() {
        return generatepwd;
    }

    /**
     * Sets the value of the generatepwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERATEPWD(String value) {
        this.generatepwd = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIGROUPS }
     *     
     */
    public TABLEOFBAPIGROUPS getGROUPS() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIGROUPS }
     *     
     */
    public void setGROUPS(TABLEOFBAPIGROUPS value) {
        this.groups = value;
    }

    /**
     * Gets the value of the groupsx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIGROUPX }
     *     
     */
    public BAPIGROUPX getGROUPSX() {
        return groupsx;
    }

    /**
     * Sets the value of the groupsx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIGROUPX }
     *     
     */
    public void setGROUPSX(BAPIGROUPX value) {
        this.groupsx = value;
    }

    /**
     * Gets the value of the logondata property.
     * 
     * @return
     *     possible object is
     *     {@link BAPILOGOND }
     *     
     */
    public BAPILOGOND getLOGONDATA() {
        return logondata;
    }

    /**
     * Sets the value of the logondata property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPILOGOND }
     *     
     */
    public void setLOGONDATA(BAPILOGOND value) {
        this.logondata = value;
    }

    /**
     * Gets the value of the logondatax property.
     * 
     * @return
     *     possible object is
     *     {@link BAPILOGONX }
     *     
     */
    public BAPILOGONX getLOGONDATAX() {
        return logondatax;
    }

    /**
     * Sets the value of the logondatax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPILOGONX }
     *     
     */
    public void setLOGONDATAX(BAPILOGONX value) {
        this.logondatax = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIPARAM }
     *     
     */
    public TABLEOFBAPIPARAM getPARAMETER() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIPARAM }
     *     
     */
    public void setPARAMETER(TABLEOFBAPIPARAM value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the parameter1 property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIPARAM1 }
     *     
     */
    public TABLEOFBAPIPARAM1 getPARAMETER1() {
        return parameter1;
    }

    /**
     * Sets the value of the parameter1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIPARAM1 }
     *     
     */
    public void setPARAMETER1(TABLEOFBAPIPARAM1 value) {
        this.parameter1 = value;
    }

    /**
     * Gets the value of the parameterx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIPARAMX }
     *     
     */
    public BAPIPARAMX getPARAMETERX() {
        return parameterx;
    }

    /**
     * Sets the value of the parameterx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIPARAMX }
     *     
     */
    public void setPARAMETERX(BAPIPARAMX value) {
        this.parameterx = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIPWD }
     *     
     */
    public BAPIPWD getPASSWORD() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIPWD }
     *     
     */
    public void setPASSWORD(BAPIPWD value) {
        this.password = value;
    }

    /**
     * Gets the value of the passwordx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIPWDX }
     *     
     */
    public BAPIPWDX getPASSWORDX() {
        return passwordx;
    }

    /**
     * Sets the value of the passwordx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIPWDX }
     *     
     */
    public void setPASSWORDX(BAPIPWDX value) {
        this.passwordx = value;
    }

    /**
     * Gets the value of the productivepwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTIVEPWD() {
        return productivepwd;
    }

    /**
     * Sets the value of the productivepwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTIVEPWD(String value) {
        this.productivepwd = value;
    }

    /**
     * Gets the value of the refuser property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIREFUS }
     *     
     */
    public BAPIREFUS getREFUSER() {
        return refuser;
    }

    /**
     * Sets the value of the refuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIREFUS }
     *     
     */
    public void setREFUSER(BAPIREFUS value) {
        this.refuser = value;
    }

    /**
     * Gets the value of the refuserx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIREFUSX }
     *     
     */
    public BAPIREFUSX getREFUSERX() {
        return refuserx;
    }

    /**
     * Sets the value of the refuserx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIREFUSX }
     *     
     */
    public void setREFUSERX(BAPIREFUSX value) {
        this.refuserx = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public TABLEOFBAPIRET2 getRETURN() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public void setRETURN(TABLEOFBAPIRET2 value) {
        this._return = value;
    }

    /**
     * Gets the value of the snc property.
     * 
     * @return
     *     possible object is
     *     {@link BAPISNCU }
     *     
     */
    public BAPISNCU getSNC() {
        return snc;
    }

    /**
     * Sets the value of the snc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPISNCU }
     *     
     */
    public void setSNC(BAPISNCU value) {
        this.snc = value;
    }

    /**
     * Gets the value of the sncx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPISNCUX }
     *     
     */
    public BAPISNCUX getSNCX() {
        return sncx;
    }

    /**
     * Sets the value of the sncx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPISNCUX }
     *     
     */
    public void setSNCX(BAPISNCUX value) {
        this.sncx = value;
    }

    /**
     * Gets the value of the uclass property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUCLASS }
     *     
     */
    public BAPIUCLASS getUCLASS() {
        return uclass;
    }

    /**
     * Sets the value of the uclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUCLASS }
     *     
     */
    public void setUCLASS(BAPIUCLASS value) {
        this.uclass = value;
    }

    /**
     * Gets the value of the uclasssys property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUCLASSSYS }
     *     
     */
    public TABLEOFBAPIUCLASSSYS getUCLASSSYS() {
        return uclasssys;
    }

    /**
     * Sets the value of the uclasssys property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUCLASSSYS }
     *     
     */
    public void setUCLASSSYS(TABLEOFBAPIUCLASSSYS value) {
        this.uclasssys = value;
    }

    /**
     * Gets the value of the uclassx property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUCLASSX }
     *     
     */
    public BAPIUCLASSX getUCLASSX() {
        return uclassx;
    }

    /**
     * Sets the value of the uclassx property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUCLASSX }
     *     
     */
    public void setUCLASSX(BAPIUCLASSX value) {
        this.uclassx = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

}
