//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIADX400 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIADX400"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="STD_NO" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="COUNTRY" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="COUNTRYISO" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="ADM_DOM" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="PRIV_DOM" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="ORGANIZATN" type="{urn:sap-com:document:sap:rfc:functions}char64"/&gt;
 *         &lt;element name="ORG_UNIT_1" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="ORG_UNIT_2" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="ORG_UNIT_3" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="ORG_UNIT_4" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="LASTNAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="FIRSTNAME" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="INITIALS" type="{urn:sap-com:document:sap:rfc:functions}char5"/&gt;
 *         &lt;element name="GENERATION" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="X_121_ADDR" type="{urn:sap-com:document:sap:rfc:functions}char15"/&gt;
 *         &lt;element name="TERM_ID" type="{urn:sap-com:document:sap:rfc:functions}char24"/&gt;
 *         &lt;element name="TERM_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="UANID" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="DDA_TYPE1" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="DDA_VALUE1" type="{urn:sap-com:document:sap:rfc:functions}char128"/&gt;
 *         &lt;element name="DDA_TYPE2" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="DDA_VALUE2" type="{urn:sap-com:document:sap:rfc:functions}char128"/&gt;
 *         &lt;element name="DDA_TYPE3" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="DDA_VALUE3" type="{urn:sap-com:document:sap:rfc:functions}char128"/&gt;
 *         &lt;element name="DDA_TYPE4" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="DDA_VALUE4" type="{urn:sap-com:document:sap:rfc:functions}char128"/&gt;
 *         &lt;element name="STD_RECIP" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="R_3_USER" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="TXT_ENCODE" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="TNEF" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="HOME_FLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="CONSNUMBER" type="{urn:sap-com:document:sap:rfc:functions}numeric3"/&gt;
 *         &lt;element name="ERRORFLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="FLG_NOUSE" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="VALID_FROM" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *         &lt;element name="VALID_TO" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIADX400", propOrder = {
    "stdno",
    "country",
    "countryiso",
    "admdom",
    "privdom",
    "organizatn",
    "orgunit1",
    "orgunit2",
    "orgunit3",
    "orgunit4",
    "lastname",
    "firstname",
    "initials",
    "generation",
    "x121ADDR",
    "termid",
    "termtype",
    "uanid",
    "ddatype1",
    "ddavalue1",
    "ddatype2",
    "ddavalue2",
    "ddatype3",
    "ddavalue3",
    "ddatype4",
    "ddavalue4",
    "stdrecip",
    "r3USER",
    "txtencode",
    "tnef",
    "homeflag",
    "consnumber",
    "errorflag",
    "flgnouse",
    "validfrom",
    "validto"
})
public class BAPIADX400 {

    @XmlElement(name = "STD_NO", required = true)
    protected String stdno;
    @XmlElement(name = "COUNTRY", required = true)
    protected String country;
    @XmlElement(name = "COUNTRYISO", required = true)
    protected String countryiso;
    @XmlElement(name = "ADM_DOM", required = true)
    protected String admdom;
    @XmlElement(name = "PRIV_DOM", required = true)
    protected String privdom;
    @XmlElement(name = "ORGANIZATN", required = true)
    protected String organizatn;
    @XmlElement(name = "ORG_UNIT_1", required = true)
    protected String orgunit1;
    @XmlElement(name = "ORG_UNIT_2", required = true)
    protected String orgunit2;
    @XmlElement(name = "ORG_UNIT_3", required = true)
    protected String orgunit3;
    @XmlElement(name = "ORG_UNIT_4", required = true)
    protected String orgunit4;
    @XmlElement(name = "LASTNAME", required = true)
    protected String lastname;
    @XmlElement(name = "FIRSTNAME", required = true)
    protected String firstname;
    @XmlElement(name = "INITIALS", required = true)
    protected String initials;
    @XmlElement(name = "GENERATION", required = true)
    protected String generation;
    @XmlElement(name = "X_121_ADDR", required = true)
    protected String x121ADDR;
    @XmlElement(name = "TERM_ID", required = true)
    protected String termid;
    @XmlElement(name = "TERM_TYPE", required = true)
    protected String termtype;
    @XmlElement(name = "UANID", required = true)
    protected String uanid;
    @XmlElement(name = "DDA_TYPE1", required = true)
    protected String ddatype1;
    @XmlElement(name = "DDA_VALUE1", required = true)
    protected String ddavalue1;
    @XmlElement(name = "DDA_TYPE2", required = true)
    protected String ddatype2;
    @XmlElement(name = "DDA_VALUE2", required = true)
    protected String ddavalue2;
    @XmlElement(name = "DDA_TYPE3", required = true)
    protected String ddatype3;
    @XmlElement(name = "DDA_VALUE3", required = true)
    protected String ddavalue3;
    @XmlElement(name = "DDA_TYPE4", required = true)
    protected String ddatype4;
    @XmlElement(name = "DDA_VALUE4", required = true)
    protected String ddavalue4;
    @XmlElement(name = "STD_RECIP", required = true)
    protected String stdrecip;
    @XmlElement(name = "R_3_USER", required = true)
    protected String r3USER;
    @XmlElement(name = "TXT_ENCODE", required = true)
    protected String txtencode;
    @XmlElement(name = "TNEF", required = true)
    protected String tnef;
    @XmlElement(name = "HOME_FLAG", required = true)
    protected String homeflag;
    @XmlElement(name = "CONSNUMBER", required = true)
    protected String consnumber;
    @XmlElement(name = "ERRORFLAG", required = true)
    protected String errorflag;
    @XmlElement(name = "FLG_NOUSE", required = true)
    protected String flgnouse;
    @XmlElement(name = "VALID_FROM", required = true)
    protected String validfrom;
    @XmlElement(name = "VALID_TO", required = true)
    protected String validto;

    /**
     * Gets the value of the stdno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTDNO() {
        return stdno;
    }

    /**
     * Sets the value of the stdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTDNO(String value) {
        this.stdno = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRY() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRY(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the countryiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRYISO() {
        return countryiso;
    }

    /**
     * Sets the value of the countryiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRYISO(String value) {
        this.countryiso = value;
    }

    /**
     * Gets the value of the admdom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMDOM() {
        return admdom;
    }

    /**
     * Sets the value of the admdom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMDOM(String value) {
        this.admdom = value;
    }

    /**
     * Gets the value of the privdom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIVDOM() {
        return privdom;
    }

    /**
     * Sets the value of the privdom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIVDOM(String value) {
        this.privdom = value;
    }

    /**
     * Gets the value of the organizatn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGANIZATN() {
        return organizatn;
    }

    /**
     * Sets the value of the organizatn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGANIZATN(String value) {
        this.organizatn = value;
    }

    /**
     * Gets the value of the orgunit1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGUNIT1() {
        return orgunit1;
    }

    /**
     * Sets the value of the orgunit1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGUNIT1(String value) {
        this.orgunit1 = value;
    }

    /**
     * Gets the value of the orgunit2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGUNIT2() {
        return orgunit2;
    }

    /**
     * Sets the value of the orgunit2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGUNIT2(String value) {
        this.orgunit2 = value;
    }

    /**
     * Gets the value of the orgunit3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGUNIT3() {
        return orgunit3;
    }

    /**
     * Sets the value of the orgunit3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGUNIT3(String value) {
        this.orgunit3 = value;
    }

    /**
     * Gets the value of the orgunit4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGUNIT4() {
        return orgunit4;
    }

    /**
     * Sets the value of the orgunit4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGUNIT4(String value) {
        this.orgunit4 = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTNAME() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTNAME(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTNAME(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the initials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINITIALS() {
        return initials;
    }

    /**
     * Sets the value of the initials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINITIALS(String value) {
        this.initials = value;
    }

    /**
     * Gets the value of the generation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERATION() {
        return generation;
    }

    /**
     * Sets the value of the generation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERATION(String value) {
        this.generation = value;
    }

    /**
     * Gets the value of the x121ADDR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX121ADDR() {
        return x121ADDR;
    }

    /**
     * Sets the value of the x121ADDR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX121ADDR(String value) {
        this.x121ADDR = value;
    }

    /**
     * Gets the value of the termid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMID() {
        return termid;
    }

    /**
     * Sets the value of the termid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMID(String value) {
        this.termid = value;
    }

    /**
     * Gets the value of the termtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMTYPE() {
        return termtype;
    }

    /**
     * Sets the value of the termtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMTYPE(String value) {
        this.termtype = value;
    }

    /**
     * Gets the value of the uanid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUANID() {
        return uanid;
    }

    /**
     * Sets the value of the uanid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUANID(String value) {
        this.uanid = value;
    }

    /**
     * Gets the value of the ddatype1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDATYPE1() {
        return ddatype1;
    }

    /**
     * Sets the value of the ddatype1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDATYPE1(String value) {
        this.ddatype1 = value;
    }

    /**
     * Gets the value of the ddavalue1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDAVALUE1() {
        return ddavalue1;
    }

    /**
     * Sets the value of the ddavalue1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDAVALUE1(String value) {
        this.ddavalue1 = value;
    }

    /**
     * Gets the value of the ddatype2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDATYPE2() {
        return ddatype2;
    }

    /**
     * Sets the value of the ddatype2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDATYPE2(String value) {
        this.ddatype2 = value;
    }

    /**
     * Gets the value of the ddavalue2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDAVALUE2() {
        return ddavalue2;
    }

    /**
     * Sets the value of the ddavalue2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDAVALUE2(String value) {
        this.ddavalue2 = value;
    }

    /**
     * Gets the value of the ddatype3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDATYPE3() {
        return ddatype3;
    }

    /**
     * Sets the value of the ddatype3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDATYPE3(String value) {
        this.ddatype3 = value;
    }

    /**
     * Gets the value of the ddavalue3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDAVALUE3() {
        return ddavalue3;
    }

    /**
     * Sets the value of the ddavalue3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDAVALUE3(String value) {
        this.ddavalue3 = value;
    }

    /**
     * Gets the value of the ddatype4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDATYPE4() {
        return ddatype4;
    }

    /**
     * Sets the value of the ddatype4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDATYPE4(String value) {
        this.ddatype4 = value;
    }

    /**
     * Gets the value of the ddavalue4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDAVALUE4() {
        return ddavalue4;
    }

    /**
     * Sets the value of the ddavalue4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDAVALUE4(String value) {
        this.ddavalue4 = value;
    }

    /**
     * Gets the value of the stdrecip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTDRECIP() {
        return stdrecip;
    }

    /**
     * Sets the value of the stdrecip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTDRECIP(String value) {
        this.stdrecip = value;
    }

    /**
     * Gets the value of the r3USER property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getR3USER() {
        return r3USER;
    }

    /**
     * Sets the value of the r3USER property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setR3USER(String value) {
        this.r3USER = value;
    }

    /**
     * Gets the value of the txtencode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXTENCODE() {
        return txtencode;
    }

    /**
     * Sets the value of the txtencode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXTENCODE(String value) {
        this.txtencode = value;
    }

    /**
     * Gets the value of the tnef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTNEF() {
        return tnef;
    }

    /**
     * Sets the value of the tnef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTNEF(String value) {
        this.tnef = value;
    }

    /**
     * Gets the value of the homeflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMEFLAG() {
        return homeflag;
    }

    /**
     * Sets the value of the homeflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMEFLAG(String value) {
        this.homeflag = value;
    }

    /**
     * Gets the value of the consnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONSNUMBER() {
        return consnumber;
    }

    /**
     * Sets the value of the consnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONSNUMBER(String value) {
        this.consnumber = value;
    }

    /**
     * Gets the value of the errorflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORFLAG() {
        return errorflag;
    }

    /**
     * Sets the value of the errorflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORFLAG(String value) {
        this.errorflag = value;
    }

    /**
     * Gets the value of the flgnouse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLGNOUSE() {
        return flgnouse;
    }

    /**
     * Sets the value of the flgnouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLGNOUSE(String value) {
        this.flgnouse = value;
    }

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDFROM() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDFROM(String value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the validto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDTO() {
        return validto;
    }

    /**
     * Sets the value of the validto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDTO(String value) {
        this.validto = value;
    }

}
