//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIADSSF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIADSSF"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="STD_NO" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="DUMMY" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="STD_RECIP" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="HOME_FLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="CONSNUMBER" type="{urn:sap-com:document:sap:rfc:functions}numeric3"/&gt;
 *         &lt;element name="RFCDEST" type="{urn:sap-com:document:sap:rfc:functions}char32"/&gt;
 *         &lt;element name="SSFIDSHORT" type="{urn:sap-com:document:sap:rfc:functions}char132"/&gt;
 *         &lt;element name="SSF_NS" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SSF_PROF" type="{urn:sap-com:document:sap:rfc:functions}char132"/&gt;
 *         &lt;element name="SSFIDPART1" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART2" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART3" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART4" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART5" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART6" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART7" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART8" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="SSFIDPART9" type="{urn:sap-com:document:sap:rfc:functions}char48"/&gt;
 *         &lt;element name="ERRORFLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="FLG_NOUSE" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="VALID_FROM" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *         &lt;element name="VALID_TO" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIADSSF", propOrder = {
    "stdno",
    "dummy",
    "stdrecip",
    "homeflag",
    "consnumber",
    "rfcdest",
    "ssfidshort",
    "ssfns",
    "ssfprof",
    "ssfidpart1",
    "ssfidpart2",
    "ssfidpart3",
    "ssfidpart4",
    "ssfidpart5",
    "ssfidpart6",
    "ssfidpart7",
    "ssfidpart8",
    "ssfidpart9",
    "errorflag",
    "flgnouse",
    "validfrom",
    "validto"
})
public class BAPIADSSF {

    @XmlElement(name = "STD_NO", required = true)
    protected String stdno;
    @XmlElement(name = "DUMMY", required = true)
    protected String dummy;
    @XmlElement(name = "STD_RECIP", required = true)
    protected String stdrecip;
    @XmlElement(name = "HOME_FLAG", required = true)
    protected String homeflag;
    @XmlElement(name = "CONSNUMBER", required = true)
    protected String consnumber;
    @XmlElement(name = "RFCDEST", required = true)
    protected String rfcdest;
    @XmlElement(name = "SSFIDSHORT", required = true)
    protected String ssfidshort;
    @XmlElement(name = "SSF_NS", required = true)
    protected String ssfns;
    @XmlElement(name = "SSF_PROF", required = true)
    protected String ssfprof;
    @XmlElement(name = "SSFIDPART1", required = true)
    protected String ssfidpart1;
    @XmlElement(name = "SSFIDPART2", required = true)
    protected String ssfidpart2;
    @XmlElement(name = "SSFIDPART3", required = true)
    protected String ssfidpart3;
    @XmlElement(name = "SSFIDPART4", required = true)
    protected String ssfidpart4;
    @XmlElement(name = "SSFIDPART5", required = true)
    protected String ssfidpart5;
    @XmlElement(name = "SSFIDPART6", required = true)
    protected String ssfidpart6;
    @XmlElement(name = "SSFIDPART7", required = true)
    protected String ssfidpart7;
    @XmlElement(name = "SSFIDPART8", required = true)
    protected String ssfidpart8;
    @XmlElement(name = "SSFIDPART9", required = true)
    protected String ssfidpart9;
    @XmlElement(name = "ERRORFLAG", required = true)
    protected String errorflag;
    @XmlElement(name = "FLG_NOUSE", required = true)
    protected String flgnouse;
    @XmlElement(name = "VALID_FROM", required = true)
    protected String validfrom;
    @XmlElement(name = "VALID_TO", required = true)
    protected String validto;

    /**
     * Gets the value of the stdno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTDNO() {
        return stdno;
    }

    /**
     * Sets the value of the stdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTDNO(String value) {
        this.stdno = value;
    }

    /**
     * Gets the value of the dummy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDUMMY() {
        return dummy;
    }

    /**
     * Sets the value of the dummy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDUMMY(String value) {
        this.dummy = value;
    }

    /**
     * Gets the value of the stdrecip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTDRECIP() {
        return stdrecip;
    }

    /**
     * Sets the value of the stdrecip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTDRECIP(String value) {
        this.stdrecip = value;
    }

    /**
     * Gets the value of the homeflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMEFLAG() {
        return homeflag;
    }

    /**
     * Sets the value of the homeflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMEFLAG(String value) {
        this.homeflag = value;
    }

    /**
     * Gets the value of the consnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONSNUMBER() {
        return consnumber;
    }

    /**
     * Sets the value of the consnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONSNUMBER(String value) {
        this.consnumber = value;
    }

    /**
     * Gets the value of the rfcdest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRFCDEST() {
        return rfcdest;
    }

    /**
     * Sets the value of the rfcdest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRFCDEST(String value) {
        this.rfcdest = value;
    }

    /**
     * Gets the value of the ssfidshort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDSHORT() {
        return ssfidshort;
    }

    /**
     * Sets the value of the ssfidshort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDSHORT(String value) {
        this.ssfidshort = value;
    }

    /**
     * Gets the value of the ssfns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFNS() {
        return ssfns;
    }

    /**
     * Sets the value of the ssfns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFNS(String value) {
        this.ssfns = value;
    }

    /**
     * Gets the value of the ssfprof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFPROF() {
        return ssfprof;
    }

    /**
     * Sets the value of the ssfprof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFPROF(String value) {
        this.ssfprof = value;
    }

    /**
     * Gets the value of the ssfidpart1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART1() {
        return ssfidpart1;
    }

    /**
     * Sets the value of the ssfidpart1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART1(String value) {
        this.ssfidpart1 = value;
    }

    /**
     * Gets the value of the ssfidpart2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART2() {
        return ssfidpart2;
    }

    /**
     * Sets the value of the ssfidpart2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART2(String value) {
        this.ssfidpart2 = value;
    }

    /**
     * Gets the value of the ssfidpart3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART3() {
        return ssfidpart3;
    }

    /**
     * Sets the value of the ssfidpart3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART3(String value) {
        this.ssfidpart3 = value;
    }

    /**
     * Gets the value of the ssfidpart4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART4() {
        return ssfidpart4;
    }

    /**
     * Sets the value of the ssfidpart4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART4(String value) {
        this.ssfidpart4 = value;
    }

    /**
     * Gets the value of the ssfidpart5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART5() {
        return ssfidpart5;
    }

    /**
     * Sets the value of the ssfidpart5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART5(String value) {
        this.ssfidpart5 = value;
    }

    /**
     * Gets the value of the ssfidpart6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART6() {
        return ssfidpart6;
    }

    /**
     * Sets the value of the ssfidpart6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART6(String value) {
        this.ssfidpart6 = value;
    }

    /**
     * Gets the value of the ssfidpart7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART7() {
        return ssfidpart7;
    }

    /**
     * Sets the value of the ssfidpart7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART7(String value) {
        this.ssfidpart7 = value;
    }

    /**
     * Gets the value of the ssfidpart8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART8() {
        return ssfidpart8;
    }

    /**
     * Sets the value of the ssfidpart8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART8(String value) {
        this.ssfidpart8 = value;
    }

    /**
     * Gets the value of the ssfidpart9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSFIDPART9() {
        return ssfidpart9;
    }

    /**
     * Sets the value of the ssfidpart9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSFIDPART9(String value) {
        this.ssfidpart9 = value;
    }

    /**
     * Gets the value of the errorflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORFLAG() {
        return errorflag;
    }

    /**
     * Sets the value of the errorflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORFLAG(String value) {
        this.errorflag = value;
    }

    /**
     * Gets the value of the flgnouse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLGNOUSE() {
        return flgnouse;
    }

    /**
     * Sets the value of the flgnouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLGNOUSE(String value) {
        this.flgnouse = value;
    }

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDFROM() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDFROM(String value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the validto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDTO() {
        return validto;
    }

    /**
     * Sets the value of the validto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDTO(String value) {
        this.validto = value;
    }

}
