//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ACTIVITYGROUPS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIAGR" minOccurs="0"/&gt;
 *         &lt;element name="ADDCOMREM" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPICOMREM" minOccurs="0"/&gt;
 *         &lt;element name="ADDFAX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADFAX" minOccurs="0"/&gt;
 *         &lt;element name="ADDPAG" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADPAG" minOccurs="0"/&gt;
 *         &lt;element name="ADDPRT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADPRT" minOccurs="0"/&gt;
 *         &lt;element name="ADDRFC" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADRFC" minOccurs="0"/&gt;
 *         &lt;element name="ADDRML" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADRML" minOccurs="0"/&gt;
 *         &lt;element name="ADDSMTP" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADSMTP" minOccurs="0"/&gt;
 *         &lt;element name="ADDSSF" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADSSF" minOccurs="0"/&gt;
 *         &lt;element name="ADDTEL" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTEL" minOccurs="0"/&gt;
 *         &lt;element name="ADDTLX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTLX" minOccurs="0"/&gt;
 *         &lt;element name="ADDTTX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTTX" minOccurs="0"/&gt;
 *         &lt;element name="ADDURI" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADURI" minOccurs="0"/&gt;
 *         &lt;element name="ADDX400" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADX400" minOccurs="0"/&gt;
 *         &lt;element name="CACHE_RESULTS" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *         &lt;element name="EXTIDHEAD" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUSEXTIDHEAD" minOccurs="0"/&gt;
 *         &lt;element name="EXTIDPART" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUSEXTIDPART" minOccurs="0"/&gt;
 *         &lt;element name="GROUPS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIGROUPS" minOccurs="0"/&gt;
 *         &lt;element name="PARAMETER" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIPARAM" minOccurs="0"/&gt;
 *         &lt;element name="PARAMETER1" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIPARAM1" minOccurs="0"/&gt;
 *         &lt;element name="PROFILES" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIPROF" minOccurs="0"/&gt;
 *         &lt;element name="RETURN" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIRET2"/&gt;
 *         &lt;element name="SYSTEMS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIRCVSYS" minOccurs="0"/&gt;
 *         &lt;element name="UCLASSSYS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUCLASSSYS" minOccurs="0"/&gt;
 *         &lt;element name="USERNAME" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activitygroups",
    "addcomrem",
    "addfax",
    "addpag",
    "addprt",
    "addrfc",
    "addrml",
    "addsmtp",
    "addssf",
    "addtel",
    "addtlx",
    "addttx",
    "adduri",
    "addx400",
    "cacheresults",
    "extidhead",
    "extidpart",
    "groups",
    "parameter",
    "parameter1",
    "profiles",
    "_return",
    "systems",
    "uclasssys",
    "username"
})
@XmlRootElement(name = "BAPI_USER_GET_DETAIL")
public class BAPIUSERGETDETAIL {

    @XmlElement(name = "ACTIVITYGROUPS")
    protected TABLEOFBAPIAGR activitygroups;
    @XmlElement(name = "ADDCOMREM")
    protected TABLEOFBAPICOMREM addcomrem;
    @XmlElement(name = "ADDFAX")
    protected TABLEOFBAPIADFAX addfax;
    @XmlElement(name = "ADDPAG")
    protected TABLEOFBAPIADPAG addpag;
    @XmlElement(name = "ADDPRT")
    protected TABLEOFBAPIADPRT addprt;
    @XmlElement(name = "ADDRFC")
    protected TABLEOFBAPIADRFC addrfc;
    @XmlElement(name = "ADDRML")
    protected TABLEOFBAPIADRML addrml;
    @XmlElement(name = "ADDSMTP")
    protected TABLEOFBAPIADSMTP addsmtp;
    @XmlElement(name = "ADDSSF")
    protected TABLEOFBAPIADSSF addssf;
    @XmlElement(name = "ADDTEL")
    protected TABLEOFBAPIADTEL addtel;
    @XmlElement(name = "ADDTLX")
    protected TABLEOFBAPIADTLX addtlx;
    @XmlElement(name = "ADDTTX")
    protected TABLEOFBAPIADTTX addttx;
    @XmlElement(name = "ADDURI")
    protected TABLEOFBAPIADURI adduri;
    @XmlElement(name = "ADDX400")
    protected TABLEOFBAPIADX400 addx400;
    @XmlElement(name = "CACHE_RESULTS")
    protected String cacheresults;
    @XmlElement(name = "EXTIDHEAD")
    protected TABLEOFBAPIUSEXTIDHEAD extidhead;
    @XmlElement(name = "EXTIDPART")
    protected TABLEOFBAPIUSEXTIDPART extidpart;
    @XmlElement(name = "GROUPS")
    protected TABLEOFBAPIGROUPS groups;
    @XmlElement(name = "PARAMETER")
    protected TABLEOFBAPIPARAM parameter;
    @XmlElement(name = "PARAMETER1")
    protected TABLEOFBAPIPARAM1 parameter1;
    @XmlElement(name = "PROFILES")
    protected TABLEOFBAPIPROF profiles;
    @XmlElement(name = "RETURN", required = true)
    protected TABLEOFBAPIRET2 _return;
    @XmlElement(name = "SYSTEMS")
    protected TABLEOFBAPIRCVSYS systems;
    @XmlElement(name = "UCLASSSYS")
    protected TABLEOFBAPIUCLASSSYS uclasssys;
    @XmlElement(name = "USERNAME", required = true)
    protected String username;

    /**
     * Gets the value of the activitygroups property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIAGR }
     *     
     */
    public TABLEOFBAPIAGR getACTIVITYGROUPS() {
        return activitygroups;
    }

    /**
     * Sets the value of the activitygroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIAGR }
     *     
     */
    public void setACTIVITYGROUPS(TABLEOFBAPIAGR value) {
        this.activitygroups = value;
    }

    /**
     * Gets the value of the addcomrem property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPICOMREM }
     *     
     */
    public TABLEOFBAPICOMREM getADDCOMREM() {
        return addcomrem;
    }

    /**
     * Sets the value of the addcomrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPICOMREM }
     *     
     */
    public void setADDCOMREM(TABLEOFBAPICOMREM value) {
        this.addcomrem = value;
    }

    /**
     * Gets the value of the addfax property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADFAX }
     *     
     */
    public TABLEOFBAPIADFAX getADDFAX() {
        return addfax;
    }

    /**
     * Sets the value of the addfax property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADFAX }
     *     
     */
    public void setADDFAX(TABLEOFBAPIADFAX value) {
        this.addfax = value;
    }

    /**
     * Gets the value of the addpag property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADPAG }
     *     
     */
    public TABLEOFBAPIADPAG getADDPAG() {
        return addpag;
    }

    /**
     * Sets the value of the addpag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADPAG }
     *     
     */
    public void setADDPAG(TABLEOFBAPIADPAG value) {
        this.addpag = value;
    }

    /**
     * Gets the value of the addprt property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADPRT }
     *     
     */
    public TABLEOFBAPIADPRT getADDPRT() {
        return addprt;
    }

    /**
     * Sets the value of the addprt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADPRT }
     *     
     */
    public void setADDPRT(TABLEOFBAPIADPRT value) {
        this.addprt = value;
    }

    /**
     * Gets the value of the addrfc property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADRFC }
     *     
     */
    public TABLEOFBAPIADRFC getADDRFC() {
        return addrfc;
    }

    /**
     * Sets the value of the addrfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADRFC }
     *     
     */
    public void setADDRFC(TABLEOFBAPIADRFC value) {
        this.addrfc = value;
    }

    /**
     * Gets the value of the addrml property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADRML }
     *     
     */
    public TABLEOFBAPIADRML getADDRML() {
        return addrml;
    }

    /**
     * Sets the value of the addrml property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADRML }
     *     
     */
    public void setADDRML(TABLEOFBAPIADRML value) {
        this.addrml = value;
    }

    /**
     * Gets the value of the addsmtp property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADSMTP }
     *     
     */
    public TABLEOFBAPIADSMTP getADDSMTP() {
        return addsmtp;
    }

    /**
     * Sets the value of the addsmtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADSMTP }
     *     
     */
    public void setADDSMTP(TABLEOFBAPIADSMTP value) {
        this.addsmtp = value;
    }

    /**
     * Gets the value of the addssf property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADSSF }
     *     
     */
    public TABLEOFBAPIADSSF getADDSSF() {
        return addssf;
    }

    /**
     * Sets the value of the addssf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADSSF }
     *     
     */
    public void setADDSSF(TABLEOFBAPIADSSF value) {
        this.addssf = value;
    }

    /**
     * Gets the value of the addtel property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTEL }
     *     
     */
    public TABLEOFBAPIADTEL getADDTEL() {
        return addtel;
    }

    /**
     * Sets the value of the addtel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTEL }
     *     
     */
    public void setADDTEL(TABLEOFBAPIADTEL value) {
        this.addtel = value;
    }

    /**
     * Gets the value of the addtlx property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTLX }
     *     
     */
    public TABLEOFBAPIADTLX getADDTLX() {
        return addtlx;
    }

    /**
     * Sets the value of the addtlx property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTLX }
     *     
     */
    public void setADDTLX(TABLEOFBAPIADTLX value) {
        this.addtlx = value;
    }

    /**
     * Gets the value of the addttx property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTTX }
     *     
     */
    public TABLEOFBAPIADTTX getADDTTX() {
        return addttx;
    }

    /**
     * Sets the value of the addttx property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTTX }
     *     
     */
    public void setADDTTX(TABLEOFBAPIADTTX value) {
        this.addttx = value;
    }

    /**
     * Gets the value of the adduri property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADURI }
     *     
     */
    public TABLEOFBAPIADURI getADDURI() {
        return adduri;
    }

    /**
     * Sets the value of the adduri property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADURI }
     *     
     */
    public void setADDURI(TABLEOFBAPIADURI value) {
        this.adduri = value;
    }

    /**
     * Gets the value of the addx400 property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADX400 }
     *     
     */
    public TABLEOFBAPIADX400 getADDX400() {
        return addx400;
    }

    /**
     * Sets the value of the addx400 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADX400 }
     *     
     */
    public void setADDX400(TABLEOFBAPIADX400 value) {
        this.addx400 = value;
    }

    /**
     * Gets the value of the cacheresults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACHERESULTS() {
        return cacheresults;
    }

    /**
     * Sets the value of the cacheresults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACHERESULTS(String value) {
        this.cacheresults = value;
    }

    /**
     * Gets the value of the extidhead property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUSEXTIDHEAD }
     *     
     */
    public TABLEOFBAPIUSEXTIDHEAD getEXTIDHEAD() {
        return extidhead;
    }

    /**
     * Sets the value of the extidhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUSEXTIDHEAD }
     *     
     */
    public void setEXTIDHEAD(TABLEOFBAPIUSEXTIDHEAD value) {
        this.extidhead = value;
    }

    /**
     * Gets the value of the extidpart property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUSEXTIDPART }
     *     
     */
    public TABLEOFBAPIUSEXTIDPART getEXTIDPART() {
        return extidpart;
    }

    /**
     * Sets the value of the extidpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUSEXTIDPART }
     *     
     */
    public void setEXTIDPART(TABLEOFBAPIUSEXTIDPART value) {
        this.extidpart = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIGROUPS }
     *     
     */
    public TABLEOFBAPIGROUPS getGROUPS() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIGROUPS }
     *     
     */
    public void setGROUPS(TABLEOFBAPIGROUPS value) {
        this.groups = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIPARAM }
     *     
     */
    public TABLEOFBAPIPARAM getPARAMETER() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIPARAM }
     *     
     */
    public void setPARAMETER(TABLEOFBAPIPARAM value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the parameter1 property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIPARAM1 }
     *     
     */
    public TABLEOFBAPIPARAM1 getPARAMETER1() {
        return parameter1;
    }

    /**
     * Sets the value of the parameter1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIPARAM1 }
     *     
     */
    public void setPARAMETER1(TABLEOFBAPIPARAM1 value) {
        this.parameter1 = value;
    }

    /**
     * Gets the value of the profiles property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIPROF }
     *     
     */
    public TABLEOFBAPIPROF getPROFILES() {
        return profiles;
    }

    /**
     * Sets the value of the profiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIPROF }
     *     
     */
    public void setPROFILES(TABLEOFBAPIPROF value) {
        this.profiles = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public TABLEOFBAPIRET2 getRETURN() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public void setRETURN(TABLEOFBAPIRET2 value) {
        this._return = value;
    }

    /**
     * Gets the value of the systems property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIRCVSYS }
     *     
     */
    public TABLEOFBAPIRCVSYS getSYSTEMS() {
        return systems;
    }

    /**
     * Sets the value of the systems property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIRCVSYS }
     *     
     */
    public void setSYSTEMS(TABLEOFBAPIRCVSYS value) {
        this.systems = value;
    }

    /**
     * Gets the value of the uclasssys property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUCLASSSYS }
     *     
     */
    public TABLEOFBAPIUCLASSSYS getUCLASSSYS() {
        return uclasssys;
    }

    /**
     * Sets the value of the uclasssys property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUCLASSSYS }
     *     
     */
    public void setUCLASSSYS(TABLEOFBAPIUCLASSSYS value) {
        this.uclasssys = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

}
