//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIUSERADMIN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIUSERADMIN"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ANAME" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="ERDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="TRDAT" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIUSERADMIN", propOrder = {
    "aname",
    "erdat",
    "trdat"
})
public class BAPIUSERADMIN {

    @XmlElement(name = "ANAME", required = true)
    protected String aname;
    @XmlElement(name = "ERDAT", required = true)
    protected String erdat;
    @XmlElement(name = "TRDAT", required = true)
    protected String trdat;

    /**
     * Gets the value of the aname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANAME() {
        return aname;
    }

    /**
     * Sets the value of the aname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANAME(String value) {
        this.aname = value;
    }

    /**
     * Gets the value of the erdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERDAT() {
        return erdat;
    }

    /**
     * Sets the value of the erdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERDAT(String value) {
        this.erdat = value;
    }

    /**
     * Gets the value of the trdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRDAT() {
        return trdat;
    }

    /**
     * Sets the value of the trdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRDAT(String value) {
        this.trdat = value;
    }

}
