//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPICOMREM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPICOMREM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="COMM_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="LANGU" type="{urn:sap-com:document:sap:rfc:functions}lang"/&gt;
 *         &lt;element name="LANGU_ISO" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="COMM_NOTES" type="{urn:sap-com:document:sap:rfc:functions}char50"/&gt;
 *         &lt;element name="CONSNUMBER" type="{urn:sap-com:document:sap:rfc:functions}numeric3"/&gt;
 *         &lt;element name="ERRORFLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPICOMREM", propOrder = {
    "commtype",
    "langu",
    "languiso",
    "commnotes",
    "consnumber",
    "errorflag"
})
public class BAPICOMREM {

    @XmlElement(name = "COMM_TYPE", required = true)
    protected String commtype;
    @XmlElement(name = "LANGU", required = true)
    protected String langu;
    @XmlElement(name = "LANGU_ISO", required = true)
    protected String languiso;
    @XmlElement(name = "COMM_NOTES", required = true)
    protected String commnotes;
    @XmlElement(name = "CONSNUMBER", required = true)
    protected String consnumber;
    @XmlElement(name = "ERRORFLAG", required = true)
    protected String errorflag;

    /**
     * Gets the value of the commtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMTYPE() {
        return commtype;
    }

    /**
     * Sets the value of the commtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMTYPE(String value) {
        this.commtype = value;
    }

    /**
     * Gets the value of the langu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGU() {
        return langu;
    }

    /**
     * Sets the value of the langu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGU(String value) {
        this.langu = value;
    }

    /**
     * Gets the value of the languiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUISO() {
        return languiso;
    }

    /**
     * Sets the value of the languiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUISO(String value) {
        this.languiso = value;
    }

    /**
     * Gets the value of the commnotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMNOTES() {
        return commnotes;
    }

    /**
     * Sets the value of the commnotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMNOTES(String value) {
        this.commnotes = value;
    }

    /**
     * Gets the value of the consnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONSNUMBER() {
        return consnumber;
    }

    /**
     * Sets the value of the consnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONSNUMBER(String value) {
        this.consnumber = value;
    }

    /**
     * Gets the value of the errorflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORFLAG() {
        return errorflag;
    }

    /**
     * Sets the value of the errorflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORFLAG(String value) {
        this.errorflag = value;
    }

}
