//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.28 at 09:18:34 PM CEST 
//


package org.crossroad.sap.wsdl.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIADCOMX complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIADCOMX"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ADTEL" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADFAX" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADTTX" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADTLX" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADSMTP" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADRML" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADX400" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADRFC" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADPRT" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADSSF" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADURI" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADPAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="ADCOMREM" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIADCOMX", propOrder = {
    "adtel",
    "adfax",
    "adttx",
    "adtlx",
    "adsmtp",
    "adrml",
    "adx400",
    "adrfc",
    "adprt",
    "adssf",
    "aduri",
    "adpag",
    "adcomrem"
})
public class BAPIADCOMX {

    @XmlElement(name = "ADTEL", required = true)
    protected String adtel;
    @XmlElement(name = "ADFAX", required = true)
    protected String adfax;
    @XmlElement(name = "ADTTX", required = true)
    protected String adttx;
    @XmlElement(name = "ADTLX", required = true)
    protected String adtlx;
    @XmlElement(name = "ADSMTP", required = true)
    protected String adsmtp;
    @XmlElement(name = "ADRML", required = true)
    protected String adrml;
    @XmlElement(name = "ADX400", required = true)
    protected String adx400;
    @XmlElement(name = "ADRFC", required = true)
    protected String adrfc;
    @XmlElement(name = "ADPRT", required = true)
    protected String adprt;
    @XmlElement(name = "ADSSF", required = true)
    protected String adssf;
    @XmlElement(name = "ADURI", required = true)
    protected String aduri;
    @XmlElement(name = "ADPAG", required = true)
    protected String adpag;
    @XmlElement(name = "ADCOMREM", required = true)
    protected String adcomrem;

    /**
     * Gets the value of the adtel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADTEL() {
        return adtel;
    }

    /**
     * Sets the value of the adtel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADTEL(String value) {
        this.adtel = value;
    }

    /**
     * Gets the value of the adfax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADFAX() {
        return adfax;
    }

    /**
     * Sets the value of the adfax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADFAX(String value) {
        this.adfax = value;
    }

    /**
     * Gets the value of the adttx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADTTX() {
        return adttx;
    }

    /**
     * Sets the value of the adttx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADTTX(String value) {
        this.adttx = value;
    }

    /**
     * Gets the value of the adtlx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADTLX() {
        return adtlx;
    }

    /**
     * Sets the value of the adtlx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADTLX(String value) {
        this.adtlx = value;
    }

    /**
     * Gets the value of the adsmtp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADSMTP() {
        return adsmtp;
    }

    /**
     * Sets the value of the adsmtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADSMTP(String value) {
        this.adsmtp = value;
    }

    /**
     * Gets the value of the adrml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADRML() {
        return adrml;
    }

    /**
     * Sets the value of the adrml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADRML(String value) {
        this.adrml = value;
    }

    /**
     * Gets the value of the adx400 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADX400() {
        return adx400;
    }

    /**
     * Sets the value of the adx400 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADX400(String value) {
        this.adx400 = value;
    }

    /**
     * Gets the value of the adrfc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADRFC() {
        return adrfc;
    }

    /**
     * Sets the value of the adrfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADRFC(String value) {
        this.adrfc = value;
    }

    /**
     * Gets the value of the adprt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADPRT() {
        return adprt;
    }

    /**
     * Sets the value of the adprt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADPRT(String value) {
        this.adprt = value;
    }

    /**
     * Gets the value of the adssf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADSSF() {
        return adssf;
    }

    /**
     * Sets the value of the adssf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADSSF(String value) {
        this.adssf = value;
    }

    /**
     * Gets the value of the aduri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADURI() {
        return aduri;
    }

    /**
     * Sets the value of the aduri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADURI(String value) {
        this.aduri = value;
    }

    /**
     * Gets the value of the adpag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADPAG() {
        return adpag;
    }

    /**
     * Sets the value of the adpag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADPAG(String value) {
        this.adpag = value;
    }

    /**
     * Gets the value of the adcomrem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADCOMREM() {
        return adcomrem;
    }

    /**
     * Sets the value of the adcomrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADCOMREM(String value) {
        this.adcomrem = value;
    }

}
