//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.26 at 11:31:01 PM CEST 
//


package org.crossroad.sap.data.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIADDR3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIADDR3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PERS_NO" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="ADDR_NO" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TITLE_P" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="FIRSTNAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="LASTNAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="BIRTH_NAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="MIDDLENAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="SECONDNAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="FULLNAME" type="{urn:sap-com:document:sap:rfc:functions}char80"/&gt;
 *         &lt;element name="FULLNAME_X" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="TITLE_ACA1" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="TITLE_ACA2" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="PREFIX1" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="PREFIX2" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="TITLE_SPPL" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="NICKNAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="INITIALS" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="NAMEFORMAT" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="NAMCOUNTRY" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="LANGU_P" type="{urn:sap-com:document:sap:rfc:functions}lang"/&gt;
 *         &lt;element name="LANGUP_ISO" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="SORT1_P" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="SORT2_P" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="DEPARTMENT" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="FUNCTION" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="BUILDING_P" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="FLOOR_P" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="ROOM_NO_P" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="INITS_SIG" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="INHOUSE_ML" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="COMM_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="TITLE" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="NAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="NAME_2" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="NAME_3" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="NAME_4" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="C_O_NAME" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="CITY" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="DISTRICT" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="CITY_NO" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="DISTRCT_NO" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="CHCKSTATUS" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="POSTL_COD1" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="POSTL_COD2" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="POSTL_COD3" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PO_BOX" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PO_BOX_CIT" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="PBOXCIT_NO" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="DELIV_DIS" type="{urn:sap-com:document:sap:rfc:functions}char15"/&gt;
 *         &lt;element name="TRANSPZONE" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="STREET" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="STREET_NO" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="STR_ABBR" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="HOUSE_NO" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="HOUSE_NO2" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="STR_SUPPL1" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="STR_SUPPL2" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="STR_SUPPL3" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="LOCATION" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="BUILDING" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="FLOOR" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="ROOM_NO" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="COUNTRY" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="COUNTRYISO" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="LANGU" type="{urn:sap-com:document:sap:rfc:functions}lang"/&gt;
 *         &lt;element name="LANGU_ISO" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="REGION" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="SORT1" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="SORT2" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="TIME_ZONE" type="{urn:sap-com:document:sap:rfc:functions}char6"/&gt;
 *         &lt;element name="TAXJURCODE" type="{urn:sap-com:document:sap:rfc:functions}char15"/&gt;
 *         &lt;element name="ADR_NOTES" type="{urn:sap-com:document:sap:rfc:functions}char50"/&gt;
 *         &lt;element name="TEL1_NUMBR" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="TEL1_EXT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="FAX_NUMBER" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="FAX_EXTENS" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="E_MAIL" type="{urn:sap-com:document:sap:rfc:functions}char241"/&gt;
 *         &lt;element name="BUILD_LONG" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="REGIOGROUP" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="HOME_CITY" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="HOMECITYNO" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *         &lt;element name="PCODE1_EXT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PCODE2_EXT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PCODE3_EXT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="PO_W_O_NO" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="PO_BOX_REG" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="POBOX_CTRY" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="PO_CTRYISO" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="DONT_USE_S" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="DONT_USE_P" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="HOUSE_NO3" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="LANGU_CR_P" type="{urn:sap-com:document:sap:rfc:functions}lang"/&gt;
 *         &lt;element name="LANGUCPISO" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="PO_BOX_LOBBY" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="DELI_SERV_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="DELI_SERV_NUMBER" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="COUNTY_CODE" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="COUNTY" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="TOWNSHIP_CODE" type="{urn:sap-com:document:sap:rfc:functions}char8"/&gt;
 *         &lt;element name="TOWNSHIP" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="XPCPT" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIADDR3", propOrder = {
    "persno",
    "addrno",
    "titlep",
    "firstname",
    "lastname",
    "birthname",
    "middlename",
    "secondname",
    "fullname",
    "fullnamex",
    "titleaca1",
    "titleaca2",
    "prefix1",
    "prefix2",
    "titlesppl",
    "nickname",
    "initials",
    "nameformat",
    "namcountry",
    "langup",
    "langupiso",
    "sort1P",
    "sort2P",
    "department",
    "function",
    "buildingp",
    "floorp",
    "roomnop",
    "initssig",
    "inhouseml",
    "commtype",
    "title",
    "name",
    "name2",
    "name3",
    "name4",
    "coname",
    "city",
    "district",
    "cityno",
    "distrctno",
    "chckstatus",
    "postlcod1",
    "postlcod2",
    "postlcod3",
    "pobox",
    "poboxcit",
    "pboxcitno",
    "delivdis",
    "transpzone",
    "street",
    "streetno",
    "strabbr",
    "houseno",
    "houseno2",
    "strsuppl1",
    "strsuppl2",
    "strsuppl3",
    "location",
    "building",
    "floor",
    "roomno",
    "country",
    "countryiso",
    "langu",
    "languiso",
    "region",
    "sort1",
    "sort2",
    "timezone",
    "taxjurcode",
    "adrnotes",
    "tel1NUMBR",
    "tel1EXT",
    "faxnumber",
    "faxextens",
    "email",
    "buildlong",
    "regiogroup",
    "homecity",
    "homecityno",
    "pcode1EXT",
    "pcode2EXT",
    "pcode3EXT",
    "powono",
    "poboxreg",
    "poboxctry",
    "poctryiso",
    "dontuses",
    "dontusep",
    "houseno3",
    "langucrp",
    "langucpiso",
    "poboxlobby",
    "deliservtype",
    "deliservnumber",
    "countycode",
    "county",
    "townshipcode",
    "township",
    "xpcpt"
})
public class BAPIADDR3 {

    @XmlElement(name = "PERS_NO", required = true)
    protected String persno;
    @XmlElement(name = "ADDR_NO", required = true)
    protected String addrno;
    @XmlElement(name = "TITLE_P", required = true)
    protected String titlep;
    @XmlElement(name = "FIRSTNAME", required = true)
    protected String firstname;
    @XmlElement(name = "LASTNAME", required = true)
    protected String lastname;
    @XmlElement(name = "BIRTH_NAME", required = true)
    protected String birthname;
    @XmlElement(name = "MIDDLENAME", required = true)
    protected String middlename;
    @XmlElement(name = "SECONDNAME", required = true)
    protected String secondname;
    @XmlElement(name = "FULLNAME", required = true)
    protected String fullname;
    @XmlElement(name = "FULLNAME_X", required = true)
    protected String fullnamex;
    @XmlElement(name = "TITLE_ACA1", required = true)
    protected String titleaca1;
    @XmlElement(name = "TITLE_ACA2", required = true)
    protected String titleaca2;
    @XmlElement(name = "PREFIX1", required = true)
    protected String prefix1;
    @XmlElement(name = "PREFIX2", required = true)
    protected String prefix2;
    @XmlElement(name = "TITLE_SPPL", required = true)
    protected String titlesppl;
    @XmlElement(name = "NICKNAME", required = true)
    protected String nickname;
    @XmlElement(name = "INITIALS", required = true)
    protected String initials;
    @XmlElement(name = "NAMEFORMAT", required = true)
    protected String nameformat;
    @XmlElement(name = "NAMCOUNTRY", required = true)
    protected String namcountry;
    @XmlElement(name = "LANGU_P", required = true)
    protected String langup;
    @XmlElement(name = "LANGUP_ISO", required = true)
    protected String langupiso;
    @XmlElement(name = "SORT1_P", required = true)
    protected String sort1P;
    @XmlElement(name = "SORT2_P", required = true)
    protected String sort2P;
    @XmlElement(name = "DEPARTMENT", required = true)
    protected String department;
    @XmlElement(name = "FUNCTION", required = true)
    protected String function;
    @XmlElement(name = "BUILDING_P", required = true)
    protected String buildingp;
    @XmlElement(name = "FLOOR_P", required = true)
    protected String floorp;
    @XmlElement(name = "ROOM_NO_P", required = true)
    protected String roomnop;
    @XmlElement(name = "INITS_SIG", required = true)
    protected String initssig;
    @XmlElement(name = "INHOUSE_ML", required = true)
    protected String inhouseml;
    @XmlElement(name = "COMM_TYPE", required = true)
    protected String commtype;
    @XmlElement(name = "TITLE", required = true)
    protected String title;
    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "NAME_2", required = true)
    protected String name2;
    @XmlElement(name = "NAME_3", required = true)
    protected String name3;
    @XmlElement(name = "NAME_4", required = true)
    protected String name4;
    @XmlElement(name = "C_O_NAME", required = true)
    protected String coname;
    @XmlElement(name = "CITY", required = true)
    protected String city;
    @XmlElement(name = "DISTRICT", required = true)
    protected String district;
    @XmlElement(name = "CITY_NO", required = true)
    protected String cityno;
    @XmlElement(name = "DISTRCT_NO", required = true)
    protected String distrctno;
    @XmlElement(name = "CHCKSTATUS", required = true)
    protected String chckstatus;
    @XmlElement(name = "POSTL_COD1", required = true)
    protected String postlcod1;
    @XmlElement(name = "POSTL_COD2", required = true)
    protected String postlcod2;
    @XmlElement(name = "POSTL_COD3", required = true)
    protected String postlcod3;
    @XmlElement(name = "PO_BOX", required = true)
    protected String pobox;
    @XmlElement(name = "PO_BOX_CIT", required = true)
    protected String poboxcit;
    @XmlElement(name = "PBOXCIT_NO", required = true)
    protected String pboxcitno;
    @XmlElement(name = "DELIV_DIS", required = true)
    protected String delivdis;
    @XmlElement(name = "TRANSPZONE", required = true)
    protected String transpzone;
    @XmlElement(name = "STREET", required = true)
    protected String street;
    @XmlElement(name = "STREET_NO", required = true)
    protected String streetno;
    @XmlElement(name = "STR_ABBR", required = true)
    protected String strabbr;
    @XmlElement(name = "HOUSE_NO", required = true)
    protected String houseno;
    @XmlElement(name = "HOUSE_NO2", required = true)
    protected String houseno2;
    @XmlElement(name = "STR_SUPPL1", required = true)
    protected String strsuppl1;
    @XmlElement(name = "STR_SUPPL2", required = true)
    protected String strsuppl2;
    @XmlElement(name = "STR_SUPPL3", required = true)
    protected String strsuppl3;
    @XmlElement(name = "LOCATION", required = true)
    protected String location;
    @XmlElement(name = "BUILDING", required = true)
    protected String building;
    @XmlElement(name = "FLOOR", required = true)
    protected String floor;
    @XmlElement(name = "ROOM_NO", required = true)
    protected String roomno;
    @XmlElement(name = "COUNTRY", required = true)
    protected String country;
    @XmlElement(name = "COUNTRYISO", required = true)
    protected String countryiso;
    @XmlElement(name = "LANGU", required = true)
    protected String langu;
    @XmlElement(name = "LANGU_ISO", required = true)
    protected String languiso;
    @XmlElement(name = "REGION", required = true)
    protected String region;
    @XmlElement(name = "SORT1", required = true)
    protected String sort1;
    @XmlElement(name = "SORT2", required = true)
    protected String sort2;
    @XmlElement(name = "TIME_ZONE", required = true)
    protected String timezone;
    @XmlElement(name = "TAXJURCODE", required = true)
    protected String taxjurcode;
    @XmlElement(name = "ADR_NOTES", required = true)
    protected String adrnotes;
    @XmlElement(name = "TEL1_NUMBR", required = true)
    protected String tel1NUMBR;
    @XmlElement(name = "TEL1_EXT", required = true)
    protected String tel1EXT;
    @XmlElement(name = "FAX_NUMBER", required = true)
    protected String faxnumber;
    @XmlElement(name = "FAX_EXTENS", required = true)
    protected String faxextens;
    @XmlElement(name = "E_MAIL", required = true)
    protected String email;
    @XmlElement(name = "BUILD_LONG", required = true)
    protected String buildlong;
    @XmlElement(name = "REGIOGROUP", required = true)
    protected String regiogroup;
    @XmlElement(name = "HOME_CITY", required = true)
    protected String homecity;
    @XmlElement(name = "HOMECITYNO", required = true)
    protected String homecityno;
    @XmlElement(name = "PCODE1_EXT", required = true)
    protected String pcode1EXT;
    @XmlElement(name = "PCODE2_EXT", required = true)
    protected String pcode2EXT;
    @XmlElement(name = "PCODE3_EXT", required = true)
    protected String pcode3EXT;
    @XmlElement(name = "PO_W_O_NO", required = true)
    protected String powono;
    @XmlElement(name = "PO_BOX_REG", required = true)
    protected String poboxreg;
    @XmlElement(name = "POBOX_CTRY", required = true)
    protected String poboxctry;
    @XmlElement(name = "PO_CTRYISO", required = true)
    protected String poctryiso;
    @XmlElement(name = "DONT_USE_S", required = true)
    protected String dontuses;
    @XmlElement(name = "DONT_USE_P", required = true)
    protected String dontusep;
    @XmlElement(name = "HOUSE_NO3", required = true)
    protected String houseno3;
    @XmlElement(name = "LANGU_CR_P", required = true)
    protected String langucrp;
    @XmlElement(name = "LANGUCPISO", required = true)
    protected String langucpiso;
    @XmlElement(name = "PO_BOX_LOBBY", required = true)
    protected String poboxlobby;
    @XmlElement(name = "DELI_SERV_TYPE", required = true)
    protected String deliservtype;
    @XmlElement(name = "DELI_SERV_NUMBER", required = true)
    protected String deliservnumber;
    @XmlElement(name = "COUNTY_CODE", required = true)
    protected String countycode;
    @XmlElement(name = "COUNTY", required = true)
    protected String county;
    @XmlElement(name = "TOWNSHIP_CODE", required = true)
    protected String townshipcode;
    @XmlElement(name = "TOWNSHIP", required = true)
    protected String township;
    @XmlElement(name = "XPCPT", required = true)
    protected String xpcpt;

    /**
     * Gets the value of the persno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERSNO() {
        return persno;
    }

    /**
     * Sets the value of the persno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERSNO(String value) {
        this.persno = value;
    }

    /**
     * Gets the value of the addrno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRNO() {
        return addrno;
    }

    /**
     * Sets the value of the addrno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRNO(String value) {
        this.addrno = value;
    }

    /**
     * Gets the value of the titlep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLEP() {
        return titlep;
    }

    /**
     * Sets the value of the titlep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLEP(String value) {
        this.titlep = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTNAME(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTNAME() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTNAME(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the birthname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIRTHNAME() {
        return birthname;
    }

    /**
     * Sets the value of the birthname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIRTHNAME(String value) {
        this.birthname = value;
    }

    /**
     * Gets the value of the middlename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIDDLENAME() {
        return middlename;
    }

    /**
     * Sets the value of the middlename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIDDLENAME(String value) {
        this.middlename = value;
    }

    /**
     * Gets the value of the secondname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECONDNAME() {
        return secondname;
    }

    /**
     * Sets the value of the secondname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECONDNAME(String value) {
        this.secondname = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFULLNAME() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFULLNAME(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the fullnamex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFULLNAMEX() {
        return fullnamex;
    }

    /**
     * Sets the value of the fullnamex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFULLNAMEX(String value) {
        this.fullnamex = value;
    }

    /**
     * Gets the value of the titleaca1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLEACA1() {
        return titleaca1;
    }

    /**
     * Sets the value of the titleaca1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLEACA1(String value) {
        this.titleaca1 = value;
    }

    /**
     * Gets the value of the titleaca2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLEACA2() {
        return titleaca2;
    }

    /**
     * Sets the value of the titleaca2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLEACA2(String value) {
        this.titleaca2 = value;
    }

    /**
     * Gets the value of the prefix1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREFIX1() {
        return prefix1;
    }

    /**
     * Sets the value of the prefix1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREFIX1(String value) {
        this.prefix1 = value;
    }

    /**
     * Gets the value of the prefix2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREFIX2() {
        return prefix2;
    }

    /**
     * Sets the value of the prefix2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREFIX2(String value) {
        this.prefix2 = value;
    }

    /**
     * Gets the value of the titlesppl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLESPPL() {
        return titlesppl;
    }

    /**
     * Sets the value of the titlesppl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLESPPL(String value) {
        this.titlesppl = value;
    }

    /**
     * Gets the value of the nickname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNICKNAME() {
        return nickname;
    }

    /**
     * Sets the value of the nickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNICKNAME(String value) {
        this.nickname = value;
    }

    /**
     * Gets the value of the initials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINITIALS() {
        return initials;
    }

    /**
     * Sets the value of the initials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINITIALS(String value) {
        this.initials = value;
    }

    /**
     * Gets the value of the nameformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAMEFORMAT() {
        return nameformat;
    }

    /**
     * Sets the value of the nameformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAMEFORMAT(String value) {
        this.nameformat = value;
    }

    /**
     * Gets the value of the namcountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAMCOUNTRY() {
        return namcountry;
    }

    /**
     * Sets the value of the namcountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAMCOUNTRY(String value) {
        this.namcountry = value;
    }

    /**
     * Gets the value of the langup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUP() {
        return langup;
    }

    /**
     * Sets the value of the langup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUP(String value) {
        this.langup = value;
    }

    /**
     * Gets the value of the langupiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUPISO() {
        return langupiso;
    }

    /**
     * Sets the value of the langupiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUPISO(String value) {
        this.langupiso = value;
    }

    /**
     * Gets the value of the sort1P property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORT1P() {
        return sort1P;
    }

    /**
     * Sets the value of the sort1P property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORT1P(String value) {
        this.sort1P = value;
    }

    /**
     * Gets the value of the sort2P property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORT2P() {
        return sort2P;
    }

    /**
     * Sets the value of the sort2P property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORT2P(String value) {
        this.sort2P = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPARTMENT() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPARTMENT(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFUNCTION() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFUNCTION(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the buildingp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUILDINGP() {
        return buildingp;
    }

    /**
     * Sets the value of the buildingp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUILDINGP(String value) {
        this.buildingp = value;
    }

    /**
     * Gets the value of the floorp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLOORP() {
        return floorp;
    }

    /**
     * Sets the value of the floorp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLOORP(String value) {
        this.floorp = value;
    }

    /**
     * Gets the value of the roomnop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROOMNOP() {
        return roomnop;
    }

    /**
     * Sets the value of the roomnop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROOMNOP(String value) {
        this.roomnop = value;
    }

    /**
     * Gets the value of the initssig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINITSSIG() {
        return initssig;
    }

    /**
     * Sets the value of the initssig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINITSSIG(String value) {
        this.initssig = value;
    }

    /**
     * Gets the value of the inhouseml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINHOUSEML() {
        return inhouseml;
    }

    /**
     * Sets the value of the inhouseml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINHOUSEML(String value) {
        this.inhouseml = value;
    }

    /**
     * Gets the value of the commtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMTYPE() {
        return commtype;
    }

    /**
     * Sets the value of the commtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMTYPE(String value) {
        this.commtype = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLE(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the name2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME2() {
        return name2;
    }

    /**
     * Sets the value of the name2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME2(String value) {
        this.name2 = value;
    }

    /**
     * Gets the value of the name3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME3() {
        return name3;
    }

    /**
     * Sets the value of the name3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME3(String value) {
        this.name3 = value;
    }

    /**
     * Gets the value of the name4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME4() {
        return name4;
    }

    /**
     * Sets the value of the name4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME4(String value) {
        this.name4 = value;
    }

    /**
     * Gets the value of the coname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONAME() {
        return coname;
    }

    /**
     * Sets the value of the coname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONAME(String value) {
        this.coname = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITY(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISTRICT() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISTRICT(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the cityno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITYNO() {
        return cityno;
    }

    /**
     * Sets the value of the cityno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITYNO(String value) {
        this.cityno = value;
    }

    /**
     * Gets the value of the distrctno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISTRCTNO() {
        return distrctno;
    }

    /**
     * Sets the value of the distrctno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISTRCTNO(String value) {
        this.distrctno = value;
    }

    /**
     * Gets the value of the chckstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHCKSTATUS() {
        return chckstatus;
    }

    /**
     * Sets the value of the chckstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHCKSTATUS(String value) {
        this.chckstatus = value;
    }

    /**
     * Gets the value of the postlcod1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTLCOD1() {
        return postlcod1;
    }

    /**
     * Sets the value of the postlcod1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTLCOD1(String value) {
        this.postlcod1 = value;
    }

    /**
     * Gets the value of the postlcod2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTLCOD2() {
        return postlcod2;
    }

    /**
     * Sets the value of the postlcod2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTLCOD2(String value) {
        this.postlcod2 = value;
    }

    /**
     * Gets the value of the postlcod3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTLCOD3() {
        return postlcod3;
    }

    /**
     * Sets the value of the postlcod3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTLCOD3(String value) {
        this.postlcod3 = value;
    }

    /**
     * Gets the value of the pobox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOBOX() {
        return pobox;
    }

    /**
     * Sets the value of the pobox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOBOX(String value) {
        this.pobox = value;
    }

    /**
     * Gets the value of the poboxcit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOBOXCIT() {
        return poboxcit;
    }

    /**
     * Sets the value of the poboxcit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOBOXCIT(String value) {
        this.poboxcit = value;
    }

    /**
     * Gets the value of the pboxcitno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBOXCITNO() {
        return pboxcitno;
    }

    /**
     * Sets the value of the pboxcitno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBOXCITNO(String value) {
        this.pboxcitno = value;
    }

    /**
     * Gets the value of the delivdis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVDIS() {
        return delivdis;
    }

    /**
     * Sets the value of the delivdis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVDIS(String value) {
        this.delivdis = value;
    }

    /**
     * Gets the value of the transpzone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSPZONE() {
        return transpzone;
    }

    /**
     * Sets the value of the transpzone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSPZONE(String value) {
        this.transpzone = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTREET() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTREET(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the streetno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTREETNO() {
        return streetno;
    }

    /**
     * Sets the value of the streetno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTREETNO(String value) {
        this.streetno = value;
    }

    /**
     * Gets the value of the strabbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABBR() {
        return strabbr;
    }

    /**
     * Sets the value of the strabbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABBR(String value) {
        this.strabbr = value;
    }

    /**
     * Gets the value of the houseno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOUSENO() {
        return houseno;
    }

    /**
     * Sets the value of the houseno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOUSENO(String value) {
        this.houseno = value;
    }

    /**
     * Gets the value of the houseno2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOUSENO2() {
        return houseno2;
    }

    /**
     * Sets the value of the houseno2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOUSENO2(String value) {
        this.houseno2 = value;
    }

    /**
     * Gets the value of the strsuppl1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRSUPPL1() {
        return strsuppl1;
    }

    /**
     * Sets the value of the strsuppl1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRSUPPL1(String value) {
        this.strsuppl1 = value;
    }

    /**
     * Gets the value of the strsuppl2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRSUPPL2() {
        return strsuppl2;
    }

    /**
     * Sets the value of the strsuppl2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRSUPPL2(String value) {
        this.strsuppl2 = value;
    }

    /**
     * Gets the value of the strsuppl3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRSUPPL3() {
        return strsuppl3;
    }

    /**
     * Sets the value of the strsuppl3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRSUPPL3(String value) {
        this.strsuppl3 = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCATION() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCATION(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUILDING() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUILDING(String value) {
        this.building = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLOOR() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLOOR(String value) {
        this.floor = value;
    }

    /**
     * Gets the value of the roomno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROOMNO() {
        return roomno;
    }

    /**
     * Sets the value of the roomno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROOMNO(String value) {
        this.roomno = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRY() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRY(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the countryiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRYISO() {
        return countryiso;
    }

    /**
     * Sets the value of the countryiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRYISO(String value) {
        this.countryiso = value;
    }

    /**
     * Gets the value of the langu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGU() {
        return langu;
    }

    /**
     * Sets the value of the langu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGU(String value) {
        this.langu = value;
    }

    /**
     * Gets the value of the languiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUISO() {
        return languiso;
    }

    /**
     * Sets the value of the languiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUISO(String value) {
        this.languiso = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGION() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGION(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the sort1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORT1() {
        return sort1;
    }

    /**
     * Sets the value of the sort1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORT1(String value) {
        this.sort1 = value;
    }

    /**
     * Gets the value of the sort2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORT2() {
        return sort2;
    }

    /**
     * Sets the value of the sort2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORT2(String value) {
        this.sort2 = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEZONE() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEZONE(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the taxjurcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXJURCODE() {
        return taxjurcode;
    }

    /**
     * Sets the value of the taxjurcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXJURCODE(String value) {
        this.taxjurcode = value;
    }

    /**
     * Gets the value of the adrnotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADRNOTES() {
        return adrnotes;
    }

    /**
     * Sets the value of the adrnotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADRNOTES(String value) {
        this.adrnotes = value;
    }

    /**
     * Gets the value of the tel1NUMBR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEL1NUMBR() {
        return tel1NUMBR;
    }

    /**
     * Sets the value of the tel1NUMBR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEL1NUMBR(String value) {
        this.tel1NUMBR = value;
    }

    /**
     * Gets the value of the tel1EXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEL1EXT() {
        return tel1EXT;
    }

    /**
     * Sets the value of the tel1EXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEL1EXT(String value) {
        this.tel1EXT = value;
    }

    /**
     * Gets the value of the faxnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAXNUMBER() {
        return faxnumber;
    }

    /**
     * Sets the value of the faxnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAXNUMBER(String value) {
        this.faxnumber = value;
    }

    /**
     * Gets the value of the faxextens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAXEXTENS() {
        return faxextens;
    }

    /**
     * Sets the value of the faxextens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAXEXTENS(String value) {
        this.faxextens = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the buildlong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUILDLONG() {
        return buildlong;
    }

    /**
     * Sets the value of the buildlong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUILDLONG(String value) {
        this.buildlong = value;
    }

    /**
     * Gets the value of the regiogroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGIOGROUP() {
        return regiogroup;
    }

    /**
     * Sets the value of the regiogroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGIOGROUP(String value) {
        this.regiogroup = value;
    }

    /**
     * Gets the value of the homecity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMECITY() {
        return homecity;
    }

    /**
     * Sets the value of the homecity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMECITY(String value) {
        this.homecity = value;
    }

    /**
     * Gets the value of the homecityno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMECITYNO() {
        return homecityno;
    }

    /**
     * Sets the value of the homecityno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMECITYNO(String value) {
        this.homecityno = value;
    }

    /**
     * Gets the value of the pcode1EXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCODE1EXT() {
        return pcode1EXT;
    }

    /**
     * Sets the value of the pcode1EXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCODE1EXT(String value) {
        this.pcode1EXT = value;
    }

    /**
     * Gets the value of the pcode2EXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCODE2EXT() {
        return pcode2EXT;
    }

    /**
     * Sets the value of the pcode2EXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCODE2EXT(String value) {
        this.pcode2EXT = value;
    }

    /**
     * Gets the value of the pcode3EXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCODE3EXT() {
        return pcode3EXT;
    }

    /**
     * Sets the value of the pcode3EXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCODE3EXT(String value) {
        this.pcode3EXT = value;
    }

    /**
     * Gets the value of the powono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOWONO() {
        return powono;
    }

    /**
     * Sets the value of the powono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOWONO(String value) {
        this.powono = value;
    }

    /**
     * Gets the value of the poboxreg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOBOXREG() {
        return poboxreg;
    }

    /**
     * Sets the value of the poboxreg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOBOXREG(String value) {
        this.poboxreg = value;
    }

    /**
     * Gets the value of the poboxctry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOBOXCTRY() {
        return poboxctry;
    }

    /**
     * Sets the value of the poboxctry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOBOXCTRY(String value) {
        this.poboxctry = value;
    }

    /**
     * Gets the value of the poctryiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOCTRYISO() {
        return poctryiso;
    }

    /**
     * Sets the value of the poctryiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOCTRYISO(String value) {
        this.poctryiso = value;
    }

    /**
     * Gets the value of the dontuses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDONTUSES() {
        return dontuses;
    }

    /**
     * Sets the value of the dontuses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDONTUSES(String value) {
        this.dontuses = value;
    }

    /**
     * Gets the value of the dontusep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDONTUSEP() {
        return dontusep;
    }

    /**
     * Sets the value of the dontusep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDONTUSEP(String value) {
        this.dontusep = value;
    }

    /**
     * Gets the value of the houseno3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOUSENO3() {
        return houseno3;
    }

    /**
     * Sets the value of the houseno3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOUSENO3(String value) {
        this.houseno3 = value;
    }

    /**
     * Gets the value of the langucrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUCRP() {
        return langucrp;
    }

    /**
     * Sets the value of the langucrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUCRP(String value) {
        this.langucrp = value;
    }

    /**
     * Gets the value of the langucpiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUCPISO() {
        return langucpiso;
    }

    /**
     * Sets the value of the langucpiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUCPISO(String value) {
        this.langucpiso = value;
    }

    /**
     * Gets the value of the poboxlobby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOBOXLOBBY() {
        return poboxlobby;
    }

    /**
     * Sets the value of the poboxlobby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOBOXLOBBY(String value) {
        this.poboxlobby = value;
    }

    /**
     * Gets the value of the deliservtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELISERVTYPE() {
        return deliservtype;
    }

    /**
     * Sets the value of the deliservtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELISERVTYPE(String value) {
        this.deliservtype = value;
    }

    /**
     * Gets the value of the deliservnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELISERVNUMBER() {
        return deliservnumber;
    }

    /**
     * Sets the value of the deliservnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELISERVNUMBER(String value) {
        this.deliservnumber = value;
    }

    /**
     * Gets the value of the countycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTYCODE() {
        return countycode;
    }

    /**
     * Sets the value of the countycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTYCODE(String value) {
        this.countycode = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTY() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTY(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the townshipcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOWNSHIPCODE() {
        return townshipcode;
    }

    /**
     * Sets the value of the townshipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOWNSHIPCODE(String value) {
        this.townshipcode = value;
    }

    /**
     * Gets the value of the township property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOWNSHIP() {
        return township;
    }

    /**
     * Sets the value of the township property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOWNSHIP(String value) {
        this.township = value;
    }

    /**
     * Gets the value of the xpcpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPCPT() {
        return xpcpt;
    }

    /**
     * Sets the value of the xpcpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPCPT(String value) {
        this.xpcpt = value;
    }

}
