//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.26 at 11:31:01 PM CEST 
//


package org.crossroad.sap.data.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ADDCOMREM" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPICOMREM" minOccurs="0"/&gt;
 *         &lt;element name="ADDFAX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADFAX" minOccurs="0"/&gt;
 *         &lt;element name="ADDPAG" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADPAG" minOccurs="0"/&gt;
 *         &lt;element name="ADDPRT" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADPRT" minOccurs="0"/&gt;
 *         &lt;element name="ADDRESS" type="{urn:sap-com:document:sap:rfc:functions}BAPIADDR3"/&gt;
 *         &lt;element name="ADDRFC" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADRFC" minOccurs="0"/&gt;
 *         &lt;element name="ADDRML" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADRML" minOccurs="0"/&gt;
 *         &lt;element name="ADDSMTP" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADSMTP" minOccurs="0"/&gt;
 *         &lt;element name="ADDSSF" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADSSF" minOccurs="0"/&gt;
 *         &lt;element name="ADDTEL" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTEL" minOccurs="0"/&gt;
 *         &lt;element name="ADDTLX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTLX" minOccurs="0"/&gt;
 *         &lt;element name="ADDTTX" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADTTX" minOccurs="0"/&gt;
 *         &lt;element name="ADDURI" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADURI" minOccurs="0"/&gt;
 *         &lt;element name="ADDX400" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIADX400" minOccurs="0"/&gt;
 *         &lt;element name="ALIAS" type="{urn:sap-com:document:sap:rfc:functions}BAPIALIAS" minOccurs="0"/&gt;
 *         &lt;element name="COMPANY" type="{urn:sap-com:document:sap:rfc:functions}BAPIUSCOMP" minOccurs="0"/&gt;
 *         &lt;element name="DEFAULTS" type="{urn:sap-com:document:sap:rfc:functions}BAPIDEFAUL" minOccurs="0"/&gt;
 *         &lt;element name="DESCRIPTION" type="{urn:sap-com:document:sap:rfc:functions}BAPIUSDESC" minOccurs="0"/&gt;
 *         &lt;element name="EXTIDHEAD" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUSEXTIDHEAD" minOccurs="0"/&gt;
 *         &lt;element name="EXTIDPART" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIUSEXTIDPART" minOccurs="0"/&gt;
 *         &lt;element name="EX_ADDRESS" type="{urn:sap-com:document:sap:rfc:functions}char10" minOccurs="0"/&gt;
 *         &lt;element name="FORCE_SYSTEM_ASSIGNMENT" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *         &lt;element name="GENERATE_PWD" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *         &lt;element name="GROUPS" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIGROUPS" minOccurs="0"/&gt;
 *         &lt;element name="LOCK_LOCALLY" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *         &lt;element name="LOGONDATA" type="{urn:sap-com:document:sap:rfc:functions}BAPILOGOND"/&gt;
 *         &lt;element name="NAME_IN" type="{urn:sap-com:document:sap:rfc:functions}BAPIBNAME" minOccurs="0"/&gt;
 *         &lt;element name="PARAMETER" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIPARAM" minOccurs="0"/&gt;
 *         &lt;element name="PARAMETER1" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIPARAM1" minOccurs="0"/&gt;
 *         &lt;element name="PASSWORD" type="{urn:sap-com:document:sap:rfc:functions}BAPIPWD"/&gt;
 *         &lt;element name="REF_USER" type="{urn:sap-com:document:sap:rfc:functions}BAPIREFUS" minOccurs="0"/&gt;
 *         &lt;element name="RETURN" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_BAPIRET2" minOccurs="0"/&gt;
 *         &lt;element name="SELF_REGISTER" type="{urn:sap-com:document:sap:rfc:functions}char1" minOccurs="0"/&gt;
 *         &lt;element name="SNC" type="{urn:sap-com:document:sap:rfc:functions}BAPISNCU" minOccurs="0"/&gt;
 *         &lt;element name="TECH_USER" type="{urn:sap-com:document:sap:rfc:functions}BAPITECHUSER" minOccurs="0"/&gt;
 *         &lt;element name="UCLASS" type="{urn:sap-com:document:sap:rfc:functions}BAPIUCLASS" minOccurs="0"/&gt;
 *         &lt;element name="USERNAME" type="{urn:sap-com:document:sap:rfc:functions}char12"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addcomrem",
    "addfax",
    "addpag",
    "addprt",
    "address",
    "addrfc",
    "addrml",
    "addsmtp",
    "addssf",
    "addtel",
    "addtlx",
    "addttx",
    "adduri",
    "addx400",
    "alias",
    "company",
    "defaults",
    "description",
    "extidhead",
    "extidpart",
    "exaddress",
    "forcesystemassignment",
    "generatepwd",
    "groups",
    "locklocally",
    "logondata",
    "namein",
    "parameter",
    "parameter1",
    "password",
    "refuser",
    "_return",
    "selfregister",
    "snc",
    "techuser",
    "uclass",
    "username"
})
@XmlRootElement(name = "BAPI_USER_CREATE1")
public class BAPIUSERCREATE1 {

    @XmlElement(name = "ADDCOMREM")
    protected TABLEOFBAPICOMREM addcomrem;
    @XmlElement(name = "ADDFAX")
    protected TABLEOFBAPIADFAX addfax;
    @XmlElement(name = "ADDPAG")
    protected TABLEOFBAPIADPAG addpag;
    @XmlElement(name = "ADDPRT")
    protected TABLEOFBAPIADPRT addprt;
    @XmlElement(name = "ADDRESS", required = true)
    protected BAPIADDR3 address;
    @XmlElement(name = "ADDRFC")
    protected TABLEOFBAPIADRFC addrfc;
    @XmlElement(name = "ADDRML")
    protected TABLEOFBAPIADRML addrml;
    @XmlElement(name = "ADDSMTP")
    protected TABLEOFBAPIADSMTP addsmtp;
    @XmlElement(name = "ADDSSF")
    protected TABLEOFBAPIADSSF addssf;
    @XmlElement(name = "ADDTEL")
    protected TABLEOFBAPIADTEL addtel;
    @XmlElement(name = "ADDTLX")
    protected TABLEOFBAPIADTLX addtlx;
    @XmlElement(name = "ADDTTX")
    protected TABLEOFBAPIADTTX addttx;
    @XmlElement(name = "ADDURI")
    protected TABLEOFBAPIADURI adduri;
    @XmlElement(name = "ADDX400")
    protected TABLEOFBAPIADX400 addx400;
    @XmlElement(name = "ALIAS")
    protected BAPIALIAS alias;
    @XmlElement(name = "COMPANY")
    protected BAPIUSCOMP company;
    @XmlElement(name = "DEFAULTS")
    protected BAPIDEFAUL defaults;
    @XmlElement(name = "DESCRIPTION")
    protected BAPIUSDESC description;
    @XmlElement(name = "EXTIDHEAD")
    protected TABLEOFBAPIUSEXTIDHEAD extidhead;
    @XmlElement(name = "EXTIDPART")
    protected TABLEOFBAPIUSEXTIDPART extidpart;
    @XmlElement(name = "EX_ADDRESS")
    protected String exaddress;
    @XmlElement(name = "FORCE_SYSTEM_ASSIGNMENT")
    protected String forcesystemassignment;
    @XmlElement(name = "GENERATE_PWD")
    protected String generatepwd;
    @XmlElement(name = "GROUPS")
    protected TABLEOFBAPIGROUPS groups;
    @XmlElement(name = "LOCK_LOCALLY")
    protected String locklocally;
    @XmlElement(name = "LOGONDATA", required = true)
    protected BAPILOGOND logondata;
    @XmlElement(name = "NAME_IN")
    protected BAPIBNAME namein;
    @XmlElement(name = "PARAMETER")
    protected TABLEOFBAPIPARAM parameter;
    @XmlElement(name = "PARAMETER1")
    protected TABLEOFBAPIPARAM1 parameter1;
    @XmlElement(name = "PASSWORD", required = true)
    protected BAPIPWD password;
    @XmlElement(name = "REF_USER")
    protected BAPIREFUS refuser;
    @XmlElement(name = "RETURN")
    protected TABLEOFBAPIRET2 _return;
    @XmlElement(name = "SELF_REGISTER")
    protected String selfregister;
    @XmlElement(name = "SNC")
    protected BAPISNCU snc;
    @XmlElement(name = "TECH_USER")
    protected BAPITECHUSER techuser;
    @XmlElement(name = "UCLASS")
    protected BAPIUCLASS uclass;
    @XmlElement(name = "USERNAME", required = true)
    protected String username;

    /**
     * Gets the value of the addcomrem property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPICOMREM }
     *     
     */
    public TABLEOFBAPICOMREM getADDCOMREM() {
        return addcomrem;
    }

    /**
     * Sets the value of the addcomrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPICOMREM }
     *     
     */
    public void setADDCOMREM(TABLEOFBAPICOMREM value) {
        this.addcomrem = value;
    }

    /**
     * Gets the value of the addfax property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADFAX }
     *     
     */
    public TABLEOFBAPIADFAX getADDFAX() {
        return addfax;
    }

    /**
     * Sets the value of the addfax property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADFAX }
     *     
     */
    public void setADDFAX(TABLEOFBAPIADFAX value) {
        this.addfax = value;
    }

    /**
     * Gets the value of the addpag property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADPAG }
     *     
     */
    public TABLEOFBAPIADPAG getADDPAG() {
        return addpag;
    }

    /**
     * Sets the value of the addpag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADPAG }
     *     
     */
    public void setADDPAG(TABLEOFBAPIADPAG value) {
        this.addpag = value;
    }

    /**
     * Gets the value of the addprt property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADPRT }
     *     
     */
    public TABLEOFBAPIADPRT getADDPRT() {
        return addprt;
    }

    /**
     * Sets the value of the addprt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADPRT }
     *     
     */
    public void setADDPRT(TABLEOFBAPIADPRT value) {
        this.addprt = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIADDR3 }
     *     
     */
    public BAPIADDR3 getADDRESS() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIADDR3 }
     *     
     */
    public void setADDRESS(BAPIADDR3 value) {
        this.address = value;
    }

    /**
     * Gets the value of the addrfc property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADRFC }
     *     
     */
    public TABLEOFBAPIADRFC getADDRFC() {
        return addrfc;
    }

    /**
     * Sets the value of the addrfc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADRFC }
     *     
     */
    public void setADDRFC(TABLEOFBAPIADRFC value) {
        this.addrfc = value;
    }

    /**
     * Gets the value of the addrml property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADRML }
     *     
     */
    public TABLEOFBAPIADRML getADDRML() {
        return addrml;
    }

    /**
     * Sets the value of the addrml property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADRML }
     *     
     */
    public void setADDRML(TABLEOFBAPIADRML value) {
        this.addrml = value;
    }

    /**
     * Gets the value of the addsmtp property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADSMTP }
     *     
     */
    public TABLEOFBAPIADSMTP getADDSMTP() {
        return addsmtp;
    }

    /**
     * Sets the value of the addsmtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADSMTP }
     *     
     */
    public void setADDSMTP(TABLEOFBAPIADSMTP value) {
        this.addsmtp = value;
    }

    /**
     * Gets the value of the addssf property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADSSF }
     *     
     */
    public TABLEOFBAPIADSSF getADDSSF() {
        return addssf;
    }

    /**
     * Sets the value of the addssf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADSSF }
     *     
     */
    public void setADDSSF(TABLEOFBAPIADSSF value) {
        this.addssf = value;
    }

    /**
     * Gets the value of the addtel property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTEL }
     *     
     */
    public TABLEOFBAPIADTEL getADDTEL() {
        return addtel;
    }

    /**
     * Sets the value of the addtel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTEL }
     *     
     */
    public void setADDTEL(TABLEOFBAPIADTEL value) {
        this.addtel = value;
    }

    /**
     * Gets the value of the addtlx property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTLX }
     *     
     */
    public TABLEOFBAPIADTLX getADDTLX() {
        return addtlx;
    }

    /**
     * Sets the value of the addtlx property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTLX }
     *     
     */
    public void setADDTLX(TABLEOFBAPIADTLX value) {
        this.addtlx = value;
    }

    /**
     * Gets the value of the addttx property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADTTX }
     *     
     */
    public TABLEOFBAPIADTTX getADDTTX() {
        return addttx;
    }

    /**
     * Sets the value of the addttx property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADTTX }
     *     
     */
    public void setADDTTX(TABLEOFBAPIADTTX value) {
        this.addttx = value;
    }

    /**
     * Gets the value of the adduri property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADURI }
     *     
     */
    public TABLEOFBAPIADURI getADDURI() {
        return adduri;
    }

    /**
     * Sets the value of the adduri property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADURI }
     *     
     */
    public void setADDURI(TABLEOFBAPIADURI value) {
        this.adduri = value;
    }

    /**
     * Gets the value of the addx400 property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIADX400 }
     *     
     */
    public TABLEOFBAPIADX400 getADDX400() {
        return addx400;
    }

    /**
     * Sets the value of the addx400 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIADX400 }
     *     
     */
    public void setADDX400(TABLEOFBAPIADX400 value) {
        this.addx400 = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIALIAS }
     *     
     */
    public BAPIALIAS getALIAS() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIALIAS }
     *     
     */
    public void setALIAS(BAPIALIAS value) {
        this.alias = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUSCOMP }
     *     
     */
    public BAPIUSCOMP getCOMPANY() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUSCOMP }
     *     
     */
    public void setCOMPANY(BAPIUSCOMP value) {
        this.company = value;
    }

    /**
     * Gets the value of the defaults property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIDEFAUL }
     *     
     */
    public BAPIDEFAUL getDEFAULTS() {
        return defaults;
    }

    /**
     * Sets the value of the defaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIDEFAUL }
     *     
     */
    public void setDEFAULTS(BAPIDEFAUL value) {
        this.defaults = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUSDESC }
     *     
     */
    public BAPIUSDESC getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUSDESC }
     *     
     */
    public void setDESCRIPTION(BAPIUSDESC value) {
        this.description = value;
    }

    /**
     * Gets the value of the extidhead property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUSEXTIDHEAD }
     *     
     */
    public TABLEOFBAPIUSEXTIDHEAD getEXTIDHEAD() {
        return extidhead;
    }

    /**
     * Sets the value of the extidhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUSEXTIDHEAD }
     *     
     */
    public void setEXTIDHEAD(TABLEOFBAPIUSEXTIDHEAD value) {
        this.extidhead = value;
    }

    /**
     * Gets the value of the extidpart property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIUSEXTIDPART }
     *     
     */
    public TABLEOFBAPIUSEXTIDPART getEXTIDPART() {
        return extidpart;
    }

    /**
     * Sets the value of the extidpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIUSEXTIDPART }
     *     
     */
    public void setEXTIDPART(TABLEOFBAPIUSEXTIDPART value) {
        this.extidpart = value;
    }

    /**
     * Gets the value of the exaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXADDRESS() {
        return exaddress;
    }

    /**
     * Sets the value of the exaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXADDRESS(String value) {
        this.exaddress = value;
    }

    /**
     * Gets the value of the forcesystemassignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORCESYSTEMASSIGNMENT() {
        return forcesystemassignment;
    }

    /**
     * Sets the value of the forcesystemassignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORCESYSTEMASSIGNMENT(String value) {
        this.forcesystemassignment = value;
    }

    /**
     * Gets the value of the generatepwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERATEPWD() {
        return generatepwd;
    }

    /**
     * Sets the value of the generatepwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERATEPWD(String value) {
        this.generatepwd = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIGROUPS }
     *     
     */
    public TABLEOFBAPIGROUPS getGROUPS() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIGROUPS }
     *     
     */
    public void setGROUPS(TABLEOFBAPIGROUPS value) {
        this.groups = value;
    }

    /**
     * Gets the value of the locklocally property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCKLOCALLY() {
        return locklocally;
    }

    /**
     * Sets the value of the locklocally property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCKLOCALLY(String value) {
        this.locklocally = value;
    }

    /**
     * Gets the value of the logondata property.
     * 
     * @return
     *     possible object is
     *     {@link BAPILOGOND }
     *     
     */
    public BAPILOGOND getLOGONDATA() {
        return logondata;
    }

    /**
     * Sets the value of the logondata property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPILOGOND }
     *     
     */
    public void setLOGONDATA(BAPILOGOND value) {
        this.logondata = value;
    }

    /**
     * Gets the value of the namein property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIBNAME }
     *     
     */
    public BAPIBNAME getNAMEIN() {
        return namein;
    }

    /**
     * Sets the value of the namein property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIBNAME }
     *     
     */
    public void setNAMEIN(BAPIBNAME value) {
        this.namein = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIPARAM }
     *     
     */
    public TABLEOFBAPIPARAM getPARAMETER() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIPARAM }
     *     
     */
    public void setPARAMETER(TABLEOFBAPIPARAM value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the parameter1 property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIPARAM1 }
     *     
     */
    public TABLEOFBAPIPARAM1 getPARAMETER1() {
        return parameter1;
    }

    /**
     * Sets the value of the parameter1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIPARAM1 }
     *     
     */
    public void setPARAMETER1(TABLEOFBAPIPARAM1 value) {
        this.parameter1 = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIPWD }
     *     
     */
    public BAPIPWD getPASSWORD() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIPWD }
     *     
     */
    public void setPASSWORD(BAPIPWD value) {
        this.password = value;
    }

    /**
     * Gets the value of the refuser property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIREFUS }
     *     
     */
    public BAPIREFUS getREFUSER() {
        return refuser;
    }

    /**
     * Sets the value of the refuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIREFUS }
     *     
     */
    public void setREFUSER(BAPIREFUS value) {
        this.refuser = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public TABLEOFBAPIRET2 getRETURN() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFBAPIRET2 }
     *     
     */
    public void setRETURN(TABLEOFBAPIRET2 value) {
        this._return = value;
    }

    /**
     * Gets the value of the selfregister property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSELFREGISTER() {
        return selfregister;
    }

    /**
     * Sets the value of the selfregister property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSELFREGISTER(String value) {
        this.selfregister = value;
    }

    /**
     * Gets the value of the snc property.
     * 
     * @return
     *     possible object is
     *     {@link BAPISNCU }
     *     
     */
    public BAPISNCU getSNC() {
        return snc;
    }

    /**
     * Sets the value of the snc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPISNCU }
     *     
     */
    public void setSNC(BAPISNCU value) {
        this.snc = value;
    }

    /**
     * Gets the value of the techuser property.
     * 
     * @return
     *     possible object is
     *     {@link BAPITECHUSER }
     *     
     */
    public BAPITECHUSER getTECHUSER() {
        return techuser;
    }

    /**
     * Sets the value of the techuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPITECHUSER }
     *     
     */
    public void setTECHUSER(BAPITECHUSER value) {
        this.techuser = value;
    }

    /**
     * Gets the value of the uclass property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIUCLASS }
     *     
     */
    public BAPIUCLASS getUCLASS() {
        return uclass;
    }

    /**
     * Sets the value of the uclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIUCLASS }
     *     
     */
    public void setUCLASS(BAPIUCLASS value) {
        this.uclass = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

}
