//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.26 at 11:31:01 PM CEST 
//


package org.crossroad.sap.data.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIADURI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIADURI"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="STD_NO" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="URI_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="URI" type="{urn:sap-com:document:sap:rfc:functions}char132"/&gt;
 *         &lt;element name="STD_RECIP" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="HOME_FLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="CONSNUMBER" type="{urn:sap-com:document:sap:rfc:functions}numeric3"/&gt;
 *         &lt;element name="URI_PART1" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART2" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART3" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART4" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART5" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART6" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART7" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART8" type="{urn:sap-com:document:sap:rfc:functions}char250"/&gt;
 *         &lt;element name="URI_PART9" type="{urn:sap-com:document:sap:rfc:functions}char48"/&gt;
 *         &lt;element name="ERRORFLAG" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="FLG_NOUSE" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="VALID_FROM" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *         &lt;element name="VALID_TO" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIADURI", propOrder = {
    "stdno",
    "uritype",
    "uri",
    "stdrecip",
    "homeflag",
    "consnumber",
    "uripart1",
    "uripart2",
    "uripart3",
    "uripart4",
    "uripart5",
    "uripart6",
    "uripart7",
    "uripart8",
    "uripart9",
    "errorflag",
    "flgnouse",
    "validfrom",
    "validto"
})
public class BAPIADURI {

    @XmlElement(name = "STD_NO", required = true)
    protected String stdno;
    @XmlElement(name = "URI_TYPE", required = true)
    protected String uritype;
    @XmlElement(name = "URI", required = true)
    protected String uri;
    @XmlElement(name = "STD_RECIP", required = true)
    protected String stdrecip;
    @XmlElement(name = "HOME_FLAG", required = true)
    protected String homeflag;
    @XmlElement(name = "CONSNUMBER", required = true)
    protected String consnumber;
    @XmlElement(name = "URI_PART1", required = true)
    protected String uripart1;
    @XmlElement(name = "URI_PART2", required = true)
    protected String uripart2;
    @XmlElement(name = "URI_PART3", required = true)
    protected String uripart3;
    @XmlElement(name = "URI_PART4", required = true)
    protected String uripart4;
    @XmlElement(name = "URI_PART5", required = true)
    protected String uripart5;
    @XmlElement(name = "URI_PART6", required = true)
    protected String uripart6;
    @XmlElement(name = "URI_PART7", required = true)
    protected String uripart7;
    @XmlElement(name = "URI_PART8", required = true)
    protected String uripart8;
    @XmlElement(name = "URI_PART9", required = true)
    protected String uripart9;
    @XmlElement(name = "ERRORFLAG", required = true)
    protected String errorflag;
    @XmlElement(name = "FLG_NOUSE", required = true)
    protected String flgnouse;
    @XmlElement(name = "VALID_FROM", required = true)
    protected String validfrom;
    @XmlElement(name = "VALID_TO", required = true)
    protected String validto;

    /**
     * Gets the value of the stdno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTDNO() {
        return stdno;
    }

    /**
     * Sets the value of the stdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTDNO(String value) {
        this.stdno = value;
    }

    /**
     * Gets the value of the uritype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURITYPE() {
        return uritype;
    }

    /**
     * Sets the value of the uritype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURITYPE(String value) {
        this.uritype = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURI() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURI(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the stdrecip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTDRECIP() {
        return stdrecip;
    }

    /**
     * Sets the value of the stdrecip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTDRECIP(String value) {
        this.stdrecip = value;
    }

    /**
     * Gets the value of the homeflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMEFLAG() {
        return homeflag;
    }

    /**
     * Sets the value of the homeflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMEFLAG(String value) {
        this.homeflag = value;
    }

    /**
     * Gets the value of the consnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONSNUMBER() {
        return consnumber;
    }

    /**
     * Sets the value of the consnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONSNUMBER(String value) {
        this.consnumber = value;
    }

    /**
     * Gets the value of the uripart1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART1() {
        return uripart1;
    }

    /**
     * Sets the value of the uripart1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART1(String value) {
        this.uripart1 = value;
    }

    /**
     * Gets the value of the uripart2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART2() {
        return uripart2;
    }

    /**
     * Sets the value of the uripart2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART2(String value) {
        this.uripart2 = value;
    }

    /**
     * Gets the value of the uripart3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART3() {
        return uripart3;
    }

    /**
     * Sets the value of the uripart3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART3(String value) {
        this.uripart3 = value;
    }

    /**
     * Gets the value of the uripart4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART4() {
        return uripart4;
    }

    /**
     * Sets the value of the uripart4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART4(String value) {
        this.uripart4 = value;
    }

    /**
     * Gets the value of the uripart5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART5() {
        return uripart5;
    }

    /**
     * Sets the value of the uripart5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART5(String value) {
        this.uripart5 = value;
    }

    /**
     * Gets the value of the uripart6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART6() {
        return uripart6;
    }

    /**
     * Sets the value of the uripart6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART6(String value) {
        this.uripart6 = value;
    }

    /**
     * Gets the value of the uripart7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART7() {
        return uripart7;
    }

    /**
     * Sets the value of the uripart7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART7(String value) {
        this.uripart7 = value;
    }

    /**
     * Gets the value of the uripart8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART8() {
        return uripart8;
    }

    /**
     * Sets the value of the uripart8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART8(String value) {
        this.uripart8 = value;
    }

    /**
     * Gets the value of the uripart9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURIPART9() {
        return uripart9;
    }

    /**
     * Sets the value of the uripart9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURIPART9(String value) {
        this.uripart9 = value;
    }

    /**
     * Gets the value of the errorflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORFLAG() {
        return errorflag;
    }

    /**
     * Sets the value of the errorflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORFLAG(String value) {
        this.errorflag = value;
    }

    /**
     * Gets the value of the flgnouse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLGNOUSE() {
        return flgnouse;
    }

    /**
     * Sets the value of the flgnouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLGNOUSE(String value) {
        this.flgnouse = value;
    }

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDFROM() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDFROM(String value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the validto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDTO() {
        return validto;
    }

    /**
     * Sets the value of the validto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDTO(String value) {
        this.validto = value;
    }

}
