//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.26 at 11:31:01 PM CEST 
//


package org.crossroad.sap.data.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BAPIPARAM1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAPIPARAM1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PARID" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="PARVA" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="PARTXT" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAPIPARAM1", propOrder = {
    "parid",
    "parva",
    "partxt"
})
public class BAPIPARAM1 {

    @XmlElement(name = "PARID", required = true)
    protected String parid;
    @XmlElement(name = "PARVA", required = true)
    protected String parva;
    @XmlElement(name = "PARTXT", required = true)
    protected String partxt;

    /**
     * Gets the value of the parid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARID() {
        return parid;
    }

    /**
     * Sets the value of the parid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARID(String value) {
        this.parid = value;
    }

    /**
     * Gets the value of the parva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARVA() {
        return parva;
    }

    /**
     * Sets the value of the parva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARVA(String value) {
        this.parva = value;
    }

    /**
     * Gets the value of the partxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTXT() {
        return partxt;
    }

    /**
     * Sets the value of the partxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTXT(String value) {
        this.partxt = value;
    }

}
