//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.26 at 11:31:01 PM CEST 
//


package org.crossroad.sap.data.idm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ET_RETURN" type="{urn:sap-com:document:sap:rfc:functions}BAPIRET2_T"/&gt;
 *         &lt;element name="ET_USERS_CHANGED" type="{urn:sap-com:document:sap:rfc:functions}SUID_TT_BNAME"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "etreturn",
    "etuserschanged"
})
@XmlRootElement(name = "SUSR_GET_CHANGED_USERSResponse")
public class SUSRGETCHANGEDUSERSResponse {

    @XmlElement(name = "ET_RETURN", required = true)
    protected BAPIRET2T etreturn;
    @XmlElement(name = "ET_USERS_CHANGED", required = true)
    protected SUIDTTBNAME etuserschanged;

    /**
     * Gets the value of the etreturn property.
     * 
     * @return
     *     possible object is
     *     {@link BAPIRET2T }
     *     
     */
    public BAPIRET2T getETRETURN() {
        return etreturn;
    }

    /**
     * Sets the value of the etreturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAPIRET2T }
     *     
     */
    public void setETRETURN(BAPIRET2T value) {
        this.etreturn = value;
    }

    /**
     * Gets the value of the etuserschanged property.
     * 
     * @return
     *     possible object is
     *     {@link SUIDTTBNAME }
     *     
     */
    public SUIDTTBNAME getETUSERSCHANGED() {
        return etuserschanged;
    }

    /**
     * Sets the value of the etuserschanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUIDTTBNAME }
     *     
     */
    public void setETUSERSCHANGED(SUIDTTBNAME value) {
        this.etuserschanged = value;
    }

}
